const $=id=>document.getElementById(id);
const els={
  app:$('app'),cameraStage:$('cameraStage'),camera:$('camera'),cameraError:$('cameraError'),shutter:$('shutter'),chatOpen:$('chatOpen'),powerSave:$('powerSaveSwitch'),modePicker:$('modePicker'),photoModeBadge:$('photoModeBadge'),
  photoStage:$('photoStage'),blurBackdrop:$('blurBackdrop'),photo:$('capturedPhoto'),selection:$('selectionCanvas'),crop:$('cropCanvas'),back:$('backButton'),hint:$('selectionHint'),
  scanFrame:$('scanFrame'),scanStatus:$('scanStatus'),scanTitle:$('scanTitle'),scanDetail:$('scanDetail'),scanProgress:$('scanProgress'),
  result:$('resultSheet'),resultKind:$('resultKind'),resultValue:$('resultValue'),qualityBadge:$('qualityBadge'),resultClose:$('resultClose'),recognizedBlock:$('recognizedBlock'),recognizedLabel:$('recognizedLabel'),recognizedFormula:$('recognizedFormula'),
  explainTranslationRow:$('explainTranslationRow'),explainLanguage:$('explainLanguageSwitch'),stepsPanel:$('stepsPanel'),stepsTitle:$('stepsTitle'),stepsList:$('stepsList'),stepCounter:$('stepCounter'),
  utilityPanel:$('utilityPanel'),utilityText:$('utilityText'),translationResult:$('translationResult'),translationSourceLabel:$('translationSourceLabel'),translationSource:$('translationSource'),translationTargetLabel:$('translationTargetLabel'),translationTarget:$('translationTarget'),colorResult:$('colorResult'),colorSwatch:$('colorSwatch'),colorHex:$('colorHex'),colorRgb:$('colorRgb'),colorHsl:$('colorHsl'),
  alternativesPanel:$('alternativesPanel'),alternativesTitle:$('alternativesTitle'),alternativeCount:$('alternativeCount'),alternativeCards:$('alternativeCards'),alternativesButton:$('alternativesButton'),copyButton:$('copyButton'),speakButton:$('speakButton'),translateActionButton:$('translateActionButton'),
  chatPanel:$('chatPanel'),chatClose:$('chatClose'),chatMessages:$('chatMessages'),chatForm:$('chatForm'),chatInput:$('chatInput'),chatLanguage:$('chatLanguageSwitch')
};
const state={stage:'camera',mode:localStorage.getItem('mathlens-mode')||'smart',stream:null,photoUrl:'',naturalWidth:0,naturalHeight:0,selectionRect:null,dragStart:null,scanning:false,currentRequest:null,latestRaw:'',latestAnalysis:null,latestText:'',latestTranslation:'',latestColor:null,alternativesOpen:false,powerSave:localStorage.getItem('mathlens-power-save')==='1',explainLanguage:localStorage.getItem('mathlens-explain-language')||'ja',chatOpen:false};
let worker=null,recognitionResolve=null,recognitionReject=null,recognitionProgress=0,tessPromise=null,utilityWorker=null,translationResolve=null,translationReject=null;
const hide=(e,v)=>e?.classList.toggle('hidden',v);const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function fmt(n){if(!Number.isFinite(n))return String(n);if(Math.abs(n)<1e-12)n=0;return Number.isInteger(n)?String(n):String(Number(n.toPrecision(10)));}
function locale(lang,key,...args){const ja={recognizing:'認識中',recognizeDetail:'複数の読み方を比較しています',noFormula:'数式として確定できませんでした',retry:'もう一度、式だけを少し広めに囲んでください',steps:'計算のしかた',alts:'別パターン',showAlts:'別パターンを見る',hideAlts:'別パターンを閉じる',normalized:s=>`記号を標準化すると ${s}`,result:v=>`結果は ${v}`,move:'両辺を整理する',divide:n=>`両辺を ${fmt(n)} で割る`,discriminant:d=>`判別式 D = ${fmt(d)}`,quadratic:'二次方程式の解の公式を使う',noReal:'実数解はありません',identity:'どの値でも成り立ちます',noSolution:'解はありません',simplify:'式を整理する',comparison:'左右をそれぞれ計算する',stepCount:n=>`${n}ステップ`,altCount:n=>`${n}候補`,chatFail:'計算式を見つけられませんでした。式だけ入力してください。'};const en={recognizing:'Recognizing',recognizeDetail:'Comparing multiple readings',noFormula:'Could not confirm a math expression',retry:'Draw a slightly wider box around only the expression',steps:'How it was solved',alts:'Alternatives',showAlts:'Show alternatives',hideAlts:'Hide alternatives',normalized:s=>`Normalize symbols: ${s}`,result:v=>`Result: ${v}`,move:'Collect terms on both sides',divide:n=>`Divide both sides by ${fmt(n)}`,discriminant:d=>`Discriminant D = ${fmt(d)}`,quadratic:'Use the quadratic formula',noReal:'No real roots',identity:'True for every value',noSolution:'No solution',simplify:'Simplify the expression',comparison:'Evaluate both sides',stepCount:n=>`${n} steps`,altCount:n=>`${n} candidates`,chatFail:'I could not find a math expression. Enter the expression itself.'};const d=lang==='en'?en:ja;return typeof d[key]==='function'?d[key](...args):d[key];}
const modeMeta={smart:{label:'スマート',hint:'調べたい範囲を囲む'},math:{label:'数式',hint:'計算したい式を囲む'},text:{label:'文字',hint:'読み取りたい文字を囲む'},translate:{label:'翻訳',hint:'翻訳したい文字を囲む'},color:{label:'色',hint:'色を調べたい範囲を囲む'}};
function setMode(mode){if(!modeMeta[mode])return;state.mode=mode;localStorage.setItem('mathlens-mode',mode);document.querySelectorAll('.mode-chip').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));els.photoModeBadge.textContent=modeMeta[mode].label;els.hint.textContent=modeMeta[mode].hint;}
function setPowerSave(enabled){state.powerSave=!!enabled;localStorage.setItem('mathlens-power-save',enabled?'1':'0');els.powerSave.checked=state.powerSave;els.app.classList.toggle('power-save',state.powerSave);ensureWorker().postMessage({type:'SET_POWER_SAVE',enabled:state.powerSave});if(!state.powerSave)setTimeout(()=>ensureWorker().postMessage({type:'WARMUP'}),700);if(state.stage==='camera'&&!state.chatOpen)startCamera();}
function setExplainLanguage(lang){state.explainLanguage=lang;localStorage.setItem('mathlens-explain-language',lang);els.explainLanguage.checked=lang==='en';els.chatLanguage.checked=lang==='en';if(state.latestRaw&&state.latestAnalysis?.type==='math'){state.latestAnalysis=analyzeMathEntries(state.latestAnalysis.ocrCandidates||[{text:state.latestRaw,source:'saved',confidence:.8}],lang);renderMath(state.latestAnalysis)}renderChatLanguageHint();}
async function startCamera(){stopCamera();hide(els.cameraError,true);if(state.chatOpen)return;try{const q=state.powerSave?{width:{ideal:1280},height:{ideal:720},frameRate:{ideal:24,max:30}}:{width:{ideal:2560},height:{ideal:1440},frameRate:{ideal:30,max:60}};state.stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},...q}});els.camera.srcObject=state.stream;await els.camera.play()}catch(e){els.cameraError.textContent='カメラを開始できません。ブラウザのカメラ権限を確認してください。';hide(els.cameraError,false)}}
function stopCamera(){state.stream?.getTracks().forEach(t=>t.stop());state.stream=null;els.camera.srcObject=null}
function fitImageRect(){const cw=innerWidth,ch=innerHeight,iw=state.naturalWidth||cw,ih=state.naturalHeight||ch,scale=Math.min(cw/iw,ch/ih),width=iw*scale,height=ih*scale;return{x:(cw-width)/2,y:(ch-height)/2,width,height,scale}}
async function capture(){if(!els.camera.videoWidth)return;const c=document.createElement('canvas');c.width=els.camera.videoWidth;c.height=els.camera.videoHeight;c.getContext('2d',{alpha:false}).drawImage(els.camera,0,0,c.width,c.height);const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',state.powerSave?.9:.96));if(!blob)return;if(state.photoUrl)URL.revokeObjectURL(state.photoUrl);state.photoUrl=URL.createObjectURL(blob);state.naturalWidth=c.width;state.naturalHeight=c.height;stopCamera();els.photo.src=state.photoUrl;els.blurBackdrop.style.backgroundImage=`url("${state.photoUrl}")`;state.selectionRect=null;state.latestRaw='';state.latestText='';state.latestTranslation='';state.latestAnalysis=null;state.stage='select';state.alternativesOpen=false;hide(els.cameraStage,true);hide(els.photoStage,false);hide(els.result,true);hide(els.scanFrame,true);hide(els.scanStatus,true);hide(els.hint,false);els.photoModeBadge.textContent=modeMeta[state.mode].label;els.hint.textContent=modeMeta[state.mode].hint;resizeSelectionCanvas();drawSelection()}
function resizeSelectionCanvas(){const dpr=Math.max(1,devicePixelRatio||1),r=els.selection.getBoundingClientRect(),w=Math.max(1,Math.round(r.width*dpr)),h=Math.max(1,Math.round(r.height*dpr));if(els.selection.width!==w||els.selection.height!==h){els.selection.width=w;els.selection.height=h}}
const pointerPoint=e=>{const r=els.selection.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};const makeRect=(a,b)=>({x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),width:Math.abs(a.x-b.x),height:Math.abs(a.y-b.y)});
function drawSelection(){resizeSelectionCanvas();const ctx=els.selection.getContext('2d'),dpr=els.selection.width/Math.max(1,els.selection.clientWidth);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,els.selection.clientWidth,els.selection.clientHeight);const r=state.selectionRect;if(!r)return;ctx.fillStyle='rgba(0,0,0,.34)';ctx.fillRect(0,0,els.selection.clientWidth,els.selection.clientHeight);ctx.clearRect(r.x,r.y,r.width,r.height);const g=ctx.createLinearGradient(r.x,r.y,r.x+r.width,r.y+r.height);['#4285f4','#9b5cff','#ea4335','#fbbc04','#34a853','#1ec8ff'].forEach((c,i,a)=>g.addColorStop(i/(a.length-1),c));ctx.strokeStyle=g;ctx.lineWidth=3;ctx.setLineDash([10,7]);ctx.strokeRect(r.x+1.5,r.y+1.5,Math.max(0,r.width-3),Math.max(0,r.height-3))}
function selectionSourceRect(r){const f=fitImageRect(),l=Math.max(r.x,f.x),top=Math.max(r.y,f.y),right=Math.min(r.x+r.width,f.x+f.width),bottom=Math.min(r.y+r.height,f.y+f.height);if(right-l<18||bottom-top<18)throw Error('small');return{sx:(l-f.x)/f.scale,sy:(top-f.y)/f.scale,sw:(right-l)/f.scale,sh:(bottom-top)/f.scale}}
async function cropSelection(r,{math=false}={}){let{sx,sy,sw,sh}=selectionSourceRect(r);const padX=sw*(math?.08:.035),padY=sh*(math?.18:.06);sx-=padX;sy-=padY;sw+=padX*2;sh+=padY*2;if(math){const ratio=1.5,current=sw/sh;if(current<ratio){const d=sh*ratio-sw;sx-=d/2;sw+=d}else if(current>3.7){const d=sw/3.7-sh;sy-=d/2;sh+=d}}sx=Math.max(0,sx);sy=Math.max(0,sy);sw=Math.min(state.naturalWidth-sx,sw);sh=Math.min(state.naturalHeight-sy,sh);const maxSide=state.powerSave?1000:1800,scale=Math.min(2.2,maxSide/Math.max(sw,sh)),out=els.crop;out.width=Math.max(96,Math.round(sw*scale));out.height=Math.max(64,Math.round(sh*scale));const ctx=out.getContext('2d',{alpha:false});ctx.fillStyle='#fff';ctx.fillRect(0,0,out.width,out.height);ctx.filter=math?'grayscale(1) contrast(1.2) brightness(1.05)':'contrast(1.08) brightness(1.03)';ctx.drawImage(els.photo,sx,sy,sw,sh,0,0,out.width,out.height);ctx.filter='none';return new Promise(res=>out.toBlob(res,'image/png'))}
function ensureWorker(){if(worker)return worker;worker=new Worker('./ocr-worker.js',{type:'module'});worker.onmessage=e=>{const m=e.data||{};if(m.type==='progress'){recognitionProgress=Math.max(recognitionProgress,Number(m.progress)||0);updateScanProgress(recognitionProgress,m.detail)}else if(m.type==='result'&&recognitionResolve&&(!m.id||m.id===state.currentRequest)){const r=recognitionResolve;recognitionResolve=recognitionReject=null;r(m)}else if(m.type==='error'&&recognitionReject&&(!m.id||m.id===state.currentRequest)){const r=recognitionReject;recognitionResolve=recognitionReject=null;r(Error(m.message||'OCR error'))}};worker.postMessage({type:'SET_POWER_SAVE',enabled:state.powerSave});return worker}
function recognizeMath(blob){const id=crypto.randomUUID();state.currentRequest=id;recognitionProgress=0;return new Promise((resolve,reject)=>{recognitionResolve=resolve;recognitionReject=reject;ensureWorker().postMessage({type:'RECOGNIZE',id,blob})})}
function ensureUtilityWorker(){if(utilityWorker)return utilityWorker;utilityWorker=new Worker('./utility-worker.js',{type:'module'});utilityWorker.onmessage=e=>{const m=e.data||{};if(m.type==='progress')updateScanProgress(Math.max(recognitionProgress,Number(m.progress)||0),m.detail);else if(m.type==='result'&&translationResolve){const r=translationResolve;translationResolve=translationReject=null;r(m.text||'')}else if(m.type==='error'&&translationReject){const r=translationReject;translationResolve=translationReject=null;r(Error(m.message||'translation error'))}};return utilityWorker}
function translateLocal(text,direction){const id=crypto.randomUUID();return new Promise((resolve,reject)=>{translationResolve=resolve;translationReject=reject;ensureUtilityWorker().postMessage({type:'TRANSLATE',id,text,direction})})}
function updateScanProgress(v,detail){recognitionProgress=Math.max(recognitionProgress,Number(v)||0);els.scanProgress.style.width=`${Math.round(Math.max(.04,Math.min(.99,recognitionProgress))*100)}%`;if(detail)els.scanDetail.textContent=detail}
function setScanning(on,detail=''){state.scanning=on;hide(els.scanFrame,!on);hide(els.scanStatus,!on);els.selection.style.pointerEvents=on?'none':'auto';if(on){recognitionProgress=0;els.scanTitle.textContent='認識中';els.scanDetail.textContent=detail||locale(state.explainLanguage,'recognizeDetail');updateScanProgress(.04)}}

async function getTesseractWorker(){if(tessPromise)return tessPromise;tessPromise=(async()=>{updateScanProgress(.08,'文字OCRを準備中');const mod=await import('https://cdn.jsdelivr.net/npm/tesseract.js@7/dist/tesseract.esm.min.js');const worker=await mod.createWorker(['jpn','eng'],mod.OEM?.LSTM_ONLY??1,{logger:m=>{if(typeof m?.progress==='number')updateScanProgress(.12+m.progress*.7,m.status||'文字を認識中')}});try{await worker.setParameters({tessedit_pageseg_mode:'6',preserve_interword_spaces:'1'})}catch{}return worker})();try{return await tessPromise}catch(e){tessPromise=null;throw e}}
async function recognizeText(blob){const w=await getTesseractWorker();updateScanProgress(.78,'文字の形を確認中');let r=await w.recognize(blob),text=String(r?.data?.text||'').trim(),conf=Number(r?.data?.confidence||0);if((text.length<2||conf<45)&&!state.powerSave){try{await w.setParameters({tessedit_pageseg_mode:'7'});const r2=await w.recognize(blob),t2=String(r2?.data?.text||'').trim(),c2=Number(r2?.data?.confidence||0);if(c2>conf){text=t2;conf=c2}await w.setParameters({tessedit_pageseg_mode:'6'})}catch{}}return{text,confidence:conf/100}}
function detectJapanese(s){return /[ぁ-んァ-ヶ一-龠々ー]/.test(s)}

function normalizeMath(input){let s=String(input||'').trim().replace(/\$+/g,'').replace(/\\left|\\right/g,'').replace(/\\,/g,'');const map={'０':'0','１':'1','２':'2','３':'3','４':'4','５':'5','６':'6','７':'7','８':'8','９':'9','＋':'+','－':'-','−':'-','–':'-','—':'-','×':'*','✕':'*','∙':'*','⋅':'*','・':'*','÷':'/','／':'/','＝':'=','（':'(','）':')','［':'(','］':')','｛':'(','｝':')','＾':'^','％':'%'};s=[...s].map(c=>map[c]??c).join('').replace(/\\times|\\cdot/g,'*').replace(/\\div/g,'/').replace(/\\pm/g,'±');for(let i=0;i<5;i++)s=s.replace(/\\frac\s*\{([^{}]+)\}\s*\{([^{}]+)\}/g,'(($1)/($2))');s=s.replace(/\\sqrt\s*\{([^{}]+)\}/g,'sqrt($1)').replace(/√\s*([0-9.]+)/g,'sqrt($1)').replace(/\^\s*\{([^{}]+)\}/g,'^($1)').replace(/[{}]/g,m=>m==='{'?'(':')');const sup={'⁰':'0','¹':'1','²':'2','³':'3','⁴':'4','⁵':'5','⁶':'6','⁷':'7','⁸':'8','⁹':'9'};s=s.replace(/[⁰¹²³⁴⁵⁶⁷⁸⁹]+/g,m=>'^'+[...m].map(x=>sup[x]).join('')).replace(/([0-9.]+)\s*%/g,'($1/100)').replace(/[;,，]/g,'').replace(/\s+/g,'').replace(/\.{3,}/g,'').replace(/(?<=\d)[oO](?=\d|$)/g,'0').replace(/(?<=\d)[lI](?=\d|$)/g,'1');if(/^[^=]+=+$/.test(s))s=s.replace(/=+$/,'');return s}
function generateCandidates(raw){const base=normalizeMath(raw),map=new Map(),add=(s,p=0,n='OCR')=>{s=normalizeMath(s);if(!s||s.length>220)return;const prev=map.get(s);if(!prev||p<prev.penalty)map.set(s,{text:s,penalty:p,note:n})};add(base,0,'OCR');if(!base)return[];add(base.replace(/(?<=\d)[xX](?=\d|\()/g,'*').replace(/(?<=\))[xX](?=\d|\()/g,'*'),.04,'x → ×');add(base.replace(/:/g,'/'),.06,': → ÷');add(base.replace(/(?<=\d)[oO]/g,'0').replace(/[oO](?=\d)/g,'0'),.06,'O → 0');add(base.replace(/(?<=\d)[sS](?=\d|$)/g,'5'),.1,'S → 5');add(base.replace(/(?<=\d)[bB](?=\d|$)/g,'8'),.1,'B → 8');add(base.replace(/\|/g,'1'),.08,'| → 1');add(base.replace(/[zZ](?=\d|[+\-*/=]|$)/g,'2'),.11,'Z → 2');return[...map.values()].slice(0,14)}
function tokenize(s){const a=[];let i=0;while(i<s.length){const c=s[i];if(/\s/.test(c)){i++;continue}if(/[\d.]/.test(c)){let j=i+1;while(j<s.length&&/[\d.]/.test(s[j]))j++;const raw=s.slice(i,j);if((raw.match(/\./g)||[]).length>1)throw Error('number');a.push({type:'number',value:Number(raw)});i=j;continue}if(/[A-Za-zπ]/.test(c)){let j=i+1;while(j<s.length&&/[A-Za-z0-9_π]/.test(s[j]))j++;a.push({type:'id',value:s.slice(i,j)});i=j;continue}if('+-*/^()=!,'.includes(c)){a.push({type:'op',value:c});i++;continue}throw Error('token')}const out=[];for(const tok of a){const prev=out.at(-1),prevEnd=prev&&(prev.type==='number'||prev.type==='id'||prev.value===')'||prev.value==='!'),nextStart=tok.type==='number'||tok.type==='id'||tok.value==='(',fn=prev?.type==='id'&&tok.value==='('&&['sqrt','sin','cos','tan','log','ln','abs'].includes(prev.value.toLowerCase());if(prevEnd&&nextStart&&!fn)out.push({type:'op',value:'*'});out.push(tok)}return out}
function parseExpressionString(s){const a=tokenize(s);let p=0;const peek=()=>a[p],take=v=>{const x=a[p];if(!x||(v&&x.value!==v))throw Error('parse');p++;return x};function primary(){const x=peek();if(!x)throw Error('primary');if(x.type==='number'){take();return{type:'num',value:x.value}}if(x.type==='id'){take();const n=x.value;if(peek()?.value==='('&&['sqrt','sin','cos','tan','log','ln','abs'].includes(n.toLowerCase())){take('(');const z=expr();take(')');return{type:'fn',name:n.toLowerCase(),arg:z}}return{type:'var',name:n}}if(x.value==='('){take('(');const n=expr();take(')');return n}throw Error('primary')}function postfix(){let n=primary();while(peek()?.value==='!'){take('!');n={type:'fact',arg:n}}return n}function unary(){if(peek()?.value==='+'||peek()?.value==='-'){const op=take().value;return{type:'unary',op,arg:unary()}}return postfix()}function power(){let l=unary();if(peek()?.value==='^'){take('^');l={type:'bin',op:'^',left:l,right:power()}}return l}function mul(){let l=power();while(peek()?.value==='*'||peek()?.value==='/'){const op=take().value;l={type:'bin',op,left:l,right:power()}}return l}function expr(){let l=mul();while(peek()?.value==='+'||peek()?.value==='-'){const op=take().value;l={type:'bin',op,left:l,right:mul()}}return l}const n=expr();if(p!==a.length)throw Error('tail');return n}
function factorial(n){if(!Number.isInteger(n)||n<0||n>170)throw Error('fact');let r=1;for(let i=2;i<=n;i++)r*=i;return r}
function evalAst(n,vars={}){if(n.type==='num')return n.value;if(n.type==='var'){const k=n.name.toLowerCase();if(k==='π'||k==='pi')return Math.PI;if(k==='e')return Math.E;if(n.name in vars)return vars[n.name];throw Error('var')}if(n.type==='unary')return n.op==='-'?-evalAst(n.arg,vars):evalAst(n.arg,vars);if(n.type==='fact')return factorial(evalAst(n.arg,vars));if(n.type==='fn'){const x=evalAst(n.arg,vars),fn={sqrt:Math.sqrt,sin:Math.sin,cos:Math.cos,tan:Math.tan,log:Math.log10,ln:Math.log,abs:Math.abs}[n.name];return fn(x)}if(n.type==='bin'){const a=evalAst(n.left,vars),b=evalAst(n.right,vars);return n.op==='+'?a+b:n.op==='-'?a-b:n.op==='*'?a*b:n.op==='/'?a/b:a**b}throw Error('eval')}
function astToString(n){if(n.type==='num')return fmt(n.value);if(n.type==='var')return n.name;if(n.type==='unary')return n.op+astToString(n.arg);if(n.type==='fact')return astToString(n.arg)+'!';if(n.type==='fn')return`${n.name}(${astToString(n.arg)})`;return`(${astToString(n.left)} ${n.op==='*'?'×':n.op==='/'?'÷':n.op} ${astToString(n.right)})`}
function collectVars(n,set=new Set()){if(n.type==='var'&&!['e','pi','π'].includes(n.name.toLowerCase()))set.add(n.name);if(n.arg)collectVars(n.arg,set);if(n.left)collectVars(n.left,set);if(n.right)collectVars(n.right,set);return set}
function poly(n,x){if(n.type==='num')return[n.value,0,0];if(n.type==='var'){if(n.name===x)return[0,1,0];if(['e','pi','π'].includes(n.name.toLowerCase()))return[evalAst(n),0,0];throw Error('var')}if(n.type==='unary'){const p=poly(n.arg,x);return n.op==='-'?p.map(v=>-v):p}if(n.type==='bin'){const a=poly(n.left,x),b=poly(n.right,x);if(n.op==='+')return a.map((v,i)=>v+b[i]);if(n.op==='-')return a.map((v,i)=>v-b[i]);if(n.op==='*'){const o=[0,0,0,0,0];for(let i=0;i<3;i++)for(let j=0;j<3;j++)o[i+j]+=a[i]*b[j];if(Math.abs(o[3])+Math.abs(o[4])>1e-10)throw Error('degree');return o.slice(0,3)}if(n.op==='/'){if(Math.abs(b[1])+Math.abs(b[2])>1e-12||Math.abs(b[0])<1e-14)throw Error('division');return a.map(v=>v/b[0])}if(n.op==='^'){const e=evalAst(n.right);if(e===0)return[1,0,0];if(e===1)return a;if(e===2){const o=[a[0]*a[0],2*a[0]*a[1],a[1]*a[1]+2*a[0]*a[2]];if(Math.abs(a[2]*a[2])+Math.abs(a[1]*a[2])>1e-12)throw Error('degree');return o}throw Error('power')}}throw Error('poly')}
function arithmeticSteps(ast,s,lang){const steps=[locale(lang,'normalized',s)];function walk(n){if(n.type==='num')return n.value;if(n.type==='bin'){const a=walk(n.left),b=walk(n.right);if(Number.isFinite(a)&&Number.isFinite(b)){const v=evalAst({type:'bin',op:n.op,left:{type:'num',value:a},right:{type:'num',value:b}});steps.push(`${fmt(a)} ${n.op==='*'?'×':n.op==='/'?'÷':n.op} ${fmt(b)} = ${fmt(v)}`);return v}}try{const v=evalAst(n);steps.push(`${astToString(n)} = ${fmt(v)}`);return v}catch{return NaN}}const v=walk(ast);if(Number.isFinite(v))steps.push(locale(lang,'result',fmt(v)));return steps}
function formatPoly(a,b,c,x){const parts=[];if(Math.abs(a)>1e-12)parts.push(`${fmt(a)}${x}²`);if(Math.abs(b)>1e-12)parts.push(`${b>=0&&parts.length?'+ ':b<0?'− ':''}${fmt(Math.abs(b))}${x}`);if(Math.abs(c)>1e-12||!parts.length)parts.push(`${c>=0&&parts.length?'+ ':c<0?'− ':''}${fmt(Math.abs(c))}`);return parts.join(' ')}
function solveCandidate(s,lang){const parts=s.split('=');if(parts.length>2)throw Error('eq');if(parts.length===2){if(!parts[0]||!parts[1])throw Error('empty-side');const l=parseExpressionString(parts[0]),r=parseExpressionString(parts[1]),vars=[...new Set([...collectVars(l),...collectVars(r)])];if(!vars.length){const a=evalAst(l),b=evalAst(r),ok=Math.abs(a-b)<1e-10;return{normalized:s,answer:ok?'✓':'≠',steps:[locale(lang,'normalized',s),locale(lang,'comparison'),`${fmt(a)} ${ok?'=':'≠'} ${fmt(b)}`],kind:'comparison'}}if(vars.length>1)throw Error('many vars');const x=vars[0],lp=poly(l,x),rp=poly(r,x),p=lp.map((v,i)=>v-rp[i]),[c,b,a]=p;if(Math.abs(a)<1e-10&&Math.abs(b)<1e-10){const identity=Math.abs(c)<1e-10;return{normalized:s,answer:locale(lang,identity?'identity':'noSolution'),steps:[locale(lang,'normalized',s),locale(lang,'move'),`${fmt(c)} = 0`],kind:'equation'}}if(Math.abs(a)<1e-10){const ans=-c/b;return{normalized:s,answer:`${x} = ${fmt(ans)}`,steps:[locale(lang,'normalized',s),locale(lang,'move'),`${fmt(b)}${x} ${c>=0?'+':'−'} ${fmt(Math.abs(c))} = 0`,`${fmt(b)}${x} = ${fmt(-c)}`,locale(lang,'divide',b),`${x} = ${fmt(ans)}`],kind:'linear'}}const d=b*b-4*a*c,steps=[locale(lang,'normalized',s),locale(lang,'move'),`${formatPoly(a,b,c,x)} = 0`,locale(lang,'discriminant',d),locale(lang,'quadratic')];if(d<0){steps.push(locale(lang,'noReal'));return{normalized:s,answer:locale(lang,'noReal'),steps,kind:'quadratic'}}const q=Math.sqrt(d),x1=(-b+q)/(2*a),x2=(-b-q)/(2*a),ans=Math.abs(x1-x2)<1e-10?`${x} = ${fmt(x1)}`:`${x} = ${fmt(x1)}, ${fmt(x2)}`;steps.push(ans);return{normalized:s,answer:ans,steps,kind:'quadratic'}}const ast=parseExpressionString(s),vars=[...collectVars(ast)];if(!vars.length){const v=evalAst(ast);if(!Number.isFinite(v))throw Error('nonfinite');return{normalized:s,answer:fmt(v),steps:arithmeticSteps(ast,s,lang),kind:'arithmetic'}}if(vars.length===1){const p=poly(ast,vars[0]),simp=formatPoly(p[2],p[1],p[0],vars[0]);return{normalized:s,answer:simp,steps:[locale(lang,'normalized',s),locale(lang,'simplify'),simp],kind:'symbolic'}}throw Error('vars')}
function analyzeMathEntries(entries,lang='ja'){
  const votes=new Map(),solved=[];for(const entry of entries||[]){const source=entry.source||'ocr',baseBoost=source.startsWith('model')?.24:source==='quick'?-.08:0;for(const c of generateCandidates(entry.text)){try{const s=solveCandidate(c.text,lang),key=s.normalized,prev=votes.get(key)||0;votes.set(key,prev+1);let score=1-c.penalty+baseBoost+(Number(entry.confidence)||0)*.1;if(['arithmetic','linear','quadratic'].includes(s.kind))score+=.3;if(s.steps.length>=2)score+=.04;solved.push({...s,score,note:`${source}${c.note&&c.note!=='OCR'?' · '+c.note:''}`,source,ocrConfidence:entry.confidence||0})}catch{}}}
  solved.forEach(s=>s.score+=((votes.get(s.normalized)||1)-1)*.13);solved.sort((a,b)=>b.score-a.score);const uniq=[];const seen=new Set();for(const s of solved){if(seen.has(s.normalized))continue;seen.add(s.normalized);uniq.push(s)}if(!uniq.length)return{type:'math',raw:entries?.[0]?.text||'',ocrCandidates:entries||[],best:{normalized:normalizeMath(entries?.[0]?.text||''),answer:locale(lang,'noFormula'),steps:[locale(lang,'retry')],score:0,note:'retry'},alternatives:[]};return{type:'math',raw:entries?.[0]?.text||'',ocrCandidates:entries||[],best:uniq[0],alternatives:uniq.slice(1,7)}
}

function resetResultPanels(){hide(els.explainTranslationRow,true);hide(els.stepsPanel,true);hide(els.utilityPanel,true);hide(els.translationResult,true);hide(els.colorResult,true);hide(els.alternativesPanel,true);hide(els.qualityBadge,true);els.resultValue.classList.remove('text-result-title');els.alternativesButton.disabled=true;els.alternativesButton.style.opacity='.35';els.copyButton.disabled=false;els.speakButton.disabled=false;els.translateActionButton.disabled=false}
function renderMath(a){resetResultPanels();const b=a.best,lang=state.explainLanguage;els.resultKind.textContent='BEST MATCH · MATH';els.resultValue.textContent=b.answer;els.recognizedLabel.textContent='認識した式';els.recognizedFormula.textContent=b.normalized||a.raw||'—';hide(els.recognizedBlock,false);hide(els.explainTranslationRow,false);hide(els.stepsPanel,false);els.stepsTitle.textContent=locale(lang,'steps');els.stepsList.replaceChildren(...b.steps.map(s=>{const li=document.createElement('li');li.textContent=s;return li}));els.stepCounter.textContent=locale(lang,'stepCount',b.steps.length);const confidence=Math.round(Math.max(0,Math.min(1,b.ocrConfidence||0))*100);els.qualityBadge.textContent=b.source?.startsWith('model')?`高精度OCR · ${confidence||90}%`:`候補検証 · ${confidence||'—'}%`;hide(els.qualityBadge,false);const alts=a.alternatives||[];els.alternativeCount.textContent=locale(lang,'altCount',alts.length);els.alternativeCards.replaceChildren(...alts.map((x,i)=>{const e=document.createElement('button');e.type='button';e.className='alt-card';const code=document.createElement('code'),strong=document.createElement('strong'),small=document.createElement('small');code.textContent=x.normalized;strong.textContent=x.answer;small.textContent=`#${i+2} · ${x.note}`;e.append(code,strong,small);e.onclick=()=>{state.latestRaw=x.normalized;state.latestAnalysis=analyzeMathEntries([{text:x.normalized,source:'selected',confidence:1}],state.explainLanguage);renderMath(state.latestAnalysis)};return e}));els.alternativesButton.disabled=!alts.length;els.alternativesButton.style.opacity=alts.length?'1':'.35';els.alternativesButton.textContent=state.alternativesOpen?locale(lang,'hideAlts'):locale(lang,'showAlts');if(state.alternativesOpen&&alts.length)hide(els.alternativesPanel,false);els.copyButton.onclick=()=>copyText(`${b.normalized}\n${b.answer}`);els.speakButton.onclick=()=>speakText(`${b.normalized}。${b.answer}`);els.translateActionButton.onclick=()=>setExplainLanguage(state.explainLanguage==='ja'?'en':'ja')}
function renderTextResult(text,confidence=.0){resetResultPanels();state.latestText=text;els.resultKind.textContent='TEXT';els.resultValue.textContent=text?'文字を認識':'文字を読めませんでした';els.resultValue.classList.add('text-result-title');els.recognizedLabel.textContent='認識結果';els.recognizedFormula.textContent=text||'—';hide(els.recognizedBlock,false);els.utilityText.textContent=text||'文字が薄い場合は、範囲を狭くしてもう一度試してください。';hide(els.utilityPanel,false);els.qualityBadge.textContent=`文字OCR · ${Math.round(confidence*100)}%`;hide(els.qualityBadge,false);els.copyButton.onclick=()=>copyText(text);els.speakButton.onclick=()=>speakText(text);els.translateActionButton.onclick=()=>translateExistingText(text);els.alternativesButton.style.display='none'}
function renderTranslation(source,target,direction){resetResultPanels();state.latestText=source;state.latestTranslation=target;els.resultKind.textContent='TRANSLATE';els.resultValue.textContent=direction==='ja-en'?'日本語 → EN':'EN → 日本語';els.resultValue.classList.add('text-result-title');hide(els.recognizedBlock,true);els.translationSourceLabel.textContent=direction==='ja-en'?'日本語':'English';els.translationTargetLabel.textContent=direction==='ja-en'?'English':'日本語';els.translationSource.textContent=source;els.translationTarget.textContent=target;hide(els.translationResult,false);els.copyButton.onclick=()=>copyText(target);els.speakButton.onclick=()=>speakText(target);els.translateActionButton.disabled=true;els.alternativesButton.style.display='none'}
function rgbToHsl(r,g,b){r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b);let h=0,s=0,l=(max+min)/2;if(max!==min){const d=max-min;s=l>.5?d/(2-max-min):d/(max+min);switch(max){case r:h=(g-b)/d+(g<b?6:0);break;case g:h=(b-r)/d+2;break;default:h=(r-g)/d+4}h/=6}return[Math.round(h*360),Math.round(s*100),Math.round(l*100)]}
function sampleColor(r){const{sx,sy,sw,sh}=selectionSourceRect(r),c=document.createElement('canvas'),size=64;c.width=c.height=size;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(els.photo,sx,sy,sw,sh,0,0,size,size);const d=ctx.getImageData(0,0,size,size).data;let rr=0,gg=0,bb=0,n=0;for(let i=0;i<d.length;i+=16){rr+=d[i];gg+=d[i+1];bb+=d[i+2];n++}rr=Math.round(rr/n);gg=Math.round(gg/n);bb=Math.round(bb/n);const hex='#'+[rr,gg,bb].map(v=>v.toString(16).padStart(2,'0')).join('').toUpperCase(),[h,s,l]=rgbToHsl(rr,gg,bb);return{r:rr,g:gg,b:bb,hex,h,s,l}}
function renderColor(c){resetResultPanels();state.latestColor=c;els.resultKind.textContent='COLOR';els.resultValue.textContent=c.hex;els.colorSwatch.style.background=c.hex;els.colorHex.textContent=c.hex;els.colorRgb.textContent=`rgb(${c.r}, ${c.g}, ${c.b})`;els.colorHsl.textContent=`hsl(${c.h}, ${c.s}%, ${c.l}%)`;hide(els.recognizedBlock,true);hide(els.colorResult,false);els.copyButton.onclick=()=>copyText(c.hex);els.speakButton.disabled=true;els.translateActionButton.disabled=true;els.alternativesButton.style.display='none'}
function copyText(text){if(!text)return;navigator.clipboard?.writeText(text).catch(()=>{})}
function speakText(text){if(!text||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=detectJapanese(text)?'ja-JP':'en-US';speechSynthesis.speak(u)}
async function translateExistingText(text){if(!text)return;setScanning(true,'翻訳モデルを準備中');try{const direction=detectJapanese(text)?'ja-en':'en-ja',target=await translateLocal(text,direction);renderTranslation(text,target,direction);hide(els.result,false)}catch(e){console.error(e);renderTextResult(text,0)}finally{setScanning(false)}}

async function processMath(blob){const o=await recognizeMath(blob),entries=(o?.candidates?.length?o.candidates:[{text:o?.text||'',source:o?.source||'ocr',confidence:o?.confidence||0}]);const a=analyzeMathEntries(entries,state.explainLanguage);state.latestRaw=a.best.normalized||o?.text||'';state.latestAnalysis=a;renderMath(a);return a}
async function processText(blob){const t=await recognizeText(blob);renderTextResult(t.text,t.confidence);return t}
async function analyzeSelection(){const r=state.selectionRect;if(!r||r.width<30||r.height<24)return;setScanning(true,state.mode==='color'?'色を分析中':'複数の読み方を比較しています');hide(els.hint,true);try{
  if(state.mode==='color'){updateScanProgress(.7,'代表色を計算中');const c=sampleColor(r);renderColor(c);state.stage='result';await sleep(120);hide(els.result,false);return}
  const mathBlob=await cropSelection(r,{math:true});
  if(state.mode==='math'){await processMath(mathBlob)}
  else if(state.mode==='text'){const textBlob=await cropSelection(r,{math:false});await processText(textBlob)}
  else if(state.mode==='translate'){const textBlob=await cropSelection(r,{math:false}),t=await recognizeText(textBlob);if(!t.text)renderTextResult('',t.confidence);else{updateScanProgress(.86,'翻訳中');const direction=detectJapanese(t.text)?'ja-en':'en-ja',target=await translateLocal(t.text,direction);renderTranslation(t.text,target,direction)}}
  else {const o=await recognizeMath(mathBlob),entries=(o?.candidates?.length?o.candidates:[{text:o?.text||'',source:o?.source||'ocr',confidence:o?.confidence||0}]),a=analyzeMathEntries(entries,state.explainLanguage);if(a.best.score>0){state.latestRaw=a.best.normalized;state.latestAnalysis=a;renderMath(a)}else{updateScanProgress(.72,'数式ではないため文字として確認中');const textBlob=await cropSelection(r,{math:false}),t=await recognizeText(textBlob);renderTextResult(t.text,t.confidence)}}
  state.stage='result';await sleep(120);hide(els.result,false)
}catch(e){console.error(e);renderTextResult('',0);state.stage='result';hide(els.result,false)}finally{setScanning(false)}}
function backOneLevel(){els.alternativesButton.style.display='';if(state.stage==='result'){state.stage='select';state.alternativesOpen=false;hide(els.result,true);hide(els.alternativesPanel,true);state.selectionRect=null;state.latestRaw='';state.latestText='';state.latestTranslation='';state.latestAnalysis=null;drawSelection();hide(els.hint,false);return}if(state.stage==='select'){state.stage='camera';state.selectionRect=null;hide(els.photoStage,true);hide(els.result,true);hide(els.cameraStage,false);startCamera()}}
function extractExpression(text){let s=String(text||'').trim().replace(/計算して|計算|解いて|求めて|答え|は何|いくつ|solve|calculate|what is|please/gi,'');s=normalizeMath(s);const direct=s.replace(/[^0-9A-Za-zπ+\-*/^()=!.]/g,'');if(direct&&/[0-9π)]/.test(direct)&&/[+\-*/=^!]/.test(direct))return direct;const matches=String(text).match(/[0-9０-９A-Za-zπ√（(][0-9０-９A-Za-zπ√＋+－−\-×*÷/^()（）=＝.!\s]{2,}/g)||[];return normalizeMath(matches.sort((a,b)=>b.length-a.length)[0]||'')}
function addChatMessage(role,text,analysis=null){const box=document.createElement('div');box.className=`message ${role}`;if(analysis){const ans=document.createElement('span');ans.className='answer';ans.textContent=analysis.best.answer;box.append(ans);const code=document.createElement('code');code.textContent=analysis.best.normalized||text;box.append(code);const ol=document.createElement('ol');analysis.best.steps.forEach(s=>{const li=document.createElement('li');li.textContent=s;ol.append(li)});box.append(ol)}else{const p=document.createElement('p');p.textContent=text;box.append(p)}els.chatMessages.append(box);els.chatMessages.scrollTop=els.chatMessages.scrollHeight}
function openChat(){if(state.chatOpen)return;state.chatOpen=true;if(state.stage==='camera')stopCamera();hide(els.chatPanel,false);requestAnimationFrame(()=>els.chatInput.focus())}
function closeChat(){if(!state.chatOpen)return;state.chatOpen=false;hide(els.chatPanel,true);if(state.stage==='camera')startCamera()}
function renderChatLanguageHint(){els.chatInput.placeholder=state.explainLanguage==='en'?'Enter a calculation or text…':'計算式や文字を入力…'}
function submitChat(){const text=els.chatInput.value.trim();if(!text)return;addChatMessage('user',text);els.chatInput.value='';if(/^文字数[:：]?/i.test(text)){const body=text.replace(/^文字数[:：]?/i,'').trim();addChatMessage('assistant',`${body.length}文字`);return}if(/^#[0-9a-f]{6}$/i.test(text)){addChatMessage('assistant',`${text.toUpperCase()} の色コードです。`);return}const expr=extractExpression(text),a=analyzeMathEntries([{text:expr,source:'chat',confidence:1}],state.explainLanguage);if(expr&&a.best.score>0)addChatMessage('assistant','',a);else addChatMessage('assistant',locale(state.explainLanguage,'chatFail'))}

els.shutter.onclick=capture;els.back.onclick=backOneLevel;els.resultClose.onclick=backOneLevel;els.powerSave.onchange=e=>setPowerSave(e.target.checked);els.modePicker.addEventListener('click',e=>{const b=e.target.closest('.mode-chip');if(b)setMode(b.dataset.mode)});els.explainLanguage.onchange=e=>setExplainLanguage(e.target.checked?'en':'ja');els.chatLanguage.onchange=e=>setExplainLanguage(e.target.checked?'en':'ja');els.alternativesButton.onclick=()=>{if(!state.latestAnalysis?.alternatives?.length)return;state.alternativesOpen=!state.alternativesOpen;hide(els.alternativesPanel,!state.alternativesOpen);els.alternativesButton.textContent=state.alternativesOpen?locale(state.explainLanguage,'hideAlts'):locale(state.explainLanguage,'showAlts')};els.chatOpen.onclick=openChat;els.chatClose.onclick=closeChat;els.chatForm.onsubmit=e=>{e.preventDefault();submitChat()};els.chatInput.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submitChat()}});
els.selection.onpointerdown=e=>{if(state.scanning||state.stage!=='select')return;els.selection.setPointerCapture(e.pointerId);state.dragStart=pointerPoint(e);state.selectionRect={x:state.dragStart.x,y:state.dragStart.y,width:0,height:0};drawSelection();hide(els.hint,true)};els.selection.onpointermove=e=>{if(state.dragStart&&!state.scanning){state.selectionRect=makeRect(state.dragStart,pointerPoint(e));drawSelection()}};els.selection.onpointerup=e=>{if(!state.dragStart||state.scanning)return;state.selectionRect=makeRect(state.dragStart,pointerPoint(e));state.dragStart=null;drawSelection();if(state.selectionRect.width>=30&&state.selectionRect.height>=24)analyzeSelection();else hide(els.hint,false)};
addEventListener('resize',()=>{if(state.stage!=='camera'){resizeSelectionCanvas();drawSelection()}});document.addEventListener('visibilitychange',()=>{if(document.hidden)stopCamera();else if(!state.chatOpen&&state.stage==='camera')startCamera()});if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));
els.powerSave.checked=state.powerSave;els.app.classList.toggle('power-save',state.powerSave);els.explainLanguage.checked=state.explainLanguage==='en';els.chatLanguage.checked=state.explainLanguage==='en';setMode(state.mode);renderChatLanguageHint();startCamera();setTimeout(()=>{ensureWorker().postMessage({type:'SET_POWER_SAVE',enabled:state.powerSave});if(!state.powerSave)ensureWorker().postMessage({type:'WARMUP'})},1200);
