const $=id=>document.getElementById(id);
const els={
  app:$('app'),cameraStage:$('cameraStage'),camera:$('camera'),cameraError:$('cameraError'),shutter:$('shutter'),chatOpen:$('chatOpen'),powerSave:$('powerSaveSwitch'),
  photoStage:$('photoStage'),blurBackdrop:$('blurBackdrop'),photo:$('capturedPhoto'),selection:$('selectionCanvas'),crop:$('cropCanvas'),back:$('backButton'),hint:$('selectionHint'),
  scanFrame:$('scanFrame'),scanStatus:$('scanStatus'),scanTitle:$('scanTitle'),scanDetail:$('scanDetail'),scanProgress:$('scanProgress'),
  result:$('resultSheet'),resultValue:$('resultValue'),resultClose:$('resultClose'),recognizedFormula:$('recognizedFormula'),stepsTitle:$('stepsTitle'),stepsList:$('stepsList'),stepCounter:$('stepCounter'),alternativesPanel:$('alternativesPanel'),alternativesTitle:$('alternativesTitle'),alternativeCount:$('alternativeCount'),alternativeCards:$('alternativeCards'),alternativesButton:$('alternativesButton'),explainLanguage:$('explainLanguageSwitch'),
  chatPanel:$('chatPanel'),chatClose:$('chatClose'),chatMessages:$('chatMessages'),chatForm:$('chatForm'),chatInput:$('chatInput'),chatLanguage:$('chatLanguageSwitch')
};
const state={stage:'camera',stream:null,photoUrl:'',naturalWidth:0,naturalHeight:0,selectionRect:null,dragStart:null,scanning:false,currentRequest:null,latestRaw:'',latestAnalysis:null,alternativesOpen:false,powerSave:localStorage.getItem('mathlens-power-save')==='1',explainLanguage:localStorage.getItem('mathlens-explain-language')||'ja',chatOpen:false};
let worker=null,recognitionResolve=null,recognitionReject=null,recognitionProgress=0;
const hide=(e,v)=>e?.classList.toggle('hidden',v);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function fmt(n){if(!Number.isFinite(n))return String(n);if(Math.abs(n)<1e-12)n=0;return Number.isInteger(n)?String(n):String(Number(n.toPrecision(10)));}
function locale(lang,key,...args){const ja={recognizing:'認識中',recognizeDetail:'数式を読み取っています',noFormula:'数式として確定できませんでした',retry:'もう一度、式だけを少し広めに囲んでください',steps:'計算のしかた',alts:'別パターン',showAlts:'別パターンを見る',hideAlts:'別パターンを閉じる',normalized:s=>`記号を標準化すると ${s}`,result:v=>`結果は ${v}`,move:'両辺を整理する',divide:n=>`両辺を ${fmt(n)} で割る`,discriminant:d=>`判別式 D = ${fmt(d)}`,quadratic:'二次方程式の解の公式を使う',noReal:'実数解はありません',identity:'どの値でも成り立ちます',noSolution:'解はありません',simplify:'式を整理する',comparison:'左右をそれぞれ計算する',stepCount:n=>`${n}ステップ`,altCount:n=>`${n}候補`,chatFail:'計算式を見つけられませんでした。式だけ入力してください。'};const en={recognizing:'Recognizing',recognizeDetail:'Reading the expression',noFormula:'Could not confirm a math expression',retry:'Draw a slightly wider box around only the expression',steps:'How it was solved',alts:'Alternatives',showAlts:'Show alternatives',hideAlts:'Hide alternatives',normalized:s=>`Normalize symbols: ${s}`,result:v=>`Result: ${v}`,move:'Collect terms on both sides',divide:n=>`Divide both sides by ${fmt(n)}`,discriminant:d=>`Discriminant D = ${fmt(d)}`,quadratic:'Use the quadratic formula',noReal:'No real roots',identity:'True for every value',noSolution:'No solution',simplify:'Simplify the expression',comparison:'Evaluate both sides',stepCount:n=>`${n} steps`,altCount:n=>`${n} candidates`,chatFail:'I could not find a math expression. Enter the expression itself.'};const d=lang==='en'?en:ja;return typeof d[key]==='function'?d[key](...args):d[key];}
function setPowerSave(enabled){state.powerSave=!!enabled;localStorage.setItem('mathlens-power-save',enabled?'1':'0');els.powerSave.checked=state.powerSave;els.app.classList.toggle('power-save',state.powerSave);ensureWorker().postMessage({type:'SET_POWER_SAVE',enabled:state.powerSave});if(!state.powerSave)setTimeout(()=>ensureWorker().postMessage({type:'WARMUP'}),700);if(state.stage==='camera'&&!state.chatOpen)startCamera();}
function setExplainLanguage(lang){state.explainLanguage=lang;localStorage.setItem('mathlens-explain-language',lang);els.explainLanguage.checked=lang==='en';els.chatLanguage.checked=lang==='en';if(state.latestRaw){state.latestAnalysis=analyzeMath(state.latestRaw,lang);renderAnalysis(state.latestAnalysis);}renderChatLanguageHint();}
async function startCamera(){stopCamera();hide(els.cameraError,true);if(state.chatOpen)return;try{const q=state.powerSave?{width:{ideal:1280},height:{ideal:720},frameRate:{ideal:24,max:30}}:{width:{ideal:2560},height:{ideal:1440},frameRate:{ideal:30,max:60}};state.stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},...q}});els.camera.srcObject=state.stream;await els.camera.play();}catch(e){els.cameraError.textContent='カメラを開始できません。ブラウザのカメラ権限を確認してください。';hide(els.cameraError,false);}}
function stopCamera(){state.stream?.getTracks().forEach(t=>t.stop());state.stream=null;els.camera.srcObject=null;}
function fitImageRect(){const cw=innerWidth,ch=innerHeight,iw=state.naturalWidth||cw,ih=state.naturalHeight||ch,scale=Math.min(cw/iw,ch/ih),width=iw*scale,height=ih*scale;return{x:(cw-width)/2,y:(ch-height)/2,width,height,scale};}
async function capture(){if(!els.camera.videoWidth)return;const c=document.createElement('canvas');c.width=els.camera.videoWidth;c.height=els.camera.videoHeight;c.getContext('2d',{alpha:false}).drawImage(els.camera,0,0,c.width,c.height);const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',state.powerSave?.9:.95));if(!blob)return;if(state.photoUrl)URL.revokeObjectURL(state.photoUrl);state.photoUrl=URL.createObjectURL(blob);state.naturalWidth=c.width;state.naturalHeight=c.height;stopCamera();els.photo.src=state.photoUrl;els.blurBackdrop.style.backgroundImage=`url("${state.photoUrl}")`;state.selectionRect=null;state.latestRaw='';state.latestAnalysis=null;state.stage='select';state.alternativesOpen=false;hide(els.cameraStage,true);hide(els.photoStage,false);hide(els.result,true);hide(els.scanFrame,true);hide(els.scanStatus,true);hide(els.hint,false);resizeSelectionCanvas();drawSelection();}
function resizeSelectionCanvas(){const dpr=Math.max(1,devicePixelRatio||1),r=els.selection.getBoundingClientRect(),w=Math.max(1,Math.round(r.width*dpr)),h=Math.max(1,Math.round(r.height*dpr));if(els.selection.width!==w||els.selection.height!==h){els.selection.width=w;els.selection.height=h;}}
const pointerPoint=e=>{const r=els.selection.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};
const makeRect=(a,b)=>({x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),width:Math.abs(a.x-b.x),height:Math.abs(a.y-b.y)});
function drawSelection(){resizeSelectionCanvas();const ctx=els.selection.getContext('2d'),dpr=els.selection.width/Math.max(1,els.selection.clientWidth);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,els.selection.clientWidth,els.selection.clientHeight);const r=state.selectionRect;if(!r)return;ctx.fillStyle='rgba(0,0,0,.34)';ctx.fillRect(0,0,els.selection.clientWidth,els.selection.clientHeight);ctx.clearRect(r.x,r.y,r.width,r.height);const g=ctx.createLinearGradient(r.x,r.y,r.x+r.width,r.y+r.height);['#4285f4','#9b5cff','#ea4335','#fbbc04','#34a853','#1ec8ff'].forEach((c,i,a)=>g.addColorStop(i/(a.length-1),c));ctx.strokeStyle=g;ctx.lineWidth=3;ctx.setLineDash([10,7]);ctx.strokeRect(r.x+1.5,r.y+1.5,Math.max(0,r.width-3),Math.max(0,r.height-3));}
async function cropSelection(r){const f=fitImageRect(),l=Math.max(r.x,f.x),top=Math.max(r.y,f.y),right=Math.min(r.x+r.width,f.x+f.width),bottom=Math.min(r.y+r.height,f.y+f.height);if(right-l<18||bottom-top<18)throw Error('small');let sx=(l-f.x)/f.scale,sy=(top-f.y)/f.scale,sw=(right-l)/f.scale,sh=(bottom-top)/f.scale;const padX=sw*.06,padY=sh*.14;sx-=padX;sy-=padY;sw+=padX*2;sh+=padY*2;const targetRatio=1.5,current=sw/sh;if(current<targetRatio){const d=sh*targetRatio-sw;sx-=d/2;sw+=d}else if(current>3.6){const d=sw/3.6-sh;sy-=d/2;sh+=d}sx=Math.max(0,sx);sy=Math.max(0,sy);sw=Math.min(state.naturalWidth-sx,sw);sh=Math.min(state.naturalHeight-sy,sh);const maxSide=state.powerSave?960:1600,scale=Math.min(2,maxSide/Math.max(sw,sh)),out=els.crop;out.width=Math.max(96,Math.round(sw*scale));out.height=Math.max(64,Math.round(sh*scale));const ctx=out.getContext('2d',{alpha:false});ctx.fillStyle='#fff';ctx.fillRect(0,0,out.width,out.height);ctx.filter='grayscale(1) contrast(1.38) brightness(1.07)';ctx.drawImage(els.photo,sx,sy,sw,sh,0,0,out.width,out.height);ctx.filter='none';return new Promise(r=>out.toBlob(r,'image/png'));}
function ensureWorker(){if(worker)return worker;worker=new Worker('./ocr-worker.js',{type:'module'});worker.onmessage=e=>{const m=e.data||{};if(m.type==='progress'){recognitionProgress=Math.max(recognitionProgress,Number(m.progress)||0);updateScanProgress(recognitionProgress,m.detail)}else if(m.type==='result'&&recognitionResolve&&(!m.id||m.id===state.currentRequest)){const resolve=recognitionResolve;recognitionResolve=recognitionReject=null;resolve(m)}else if(m.type==='error'&&recognitionReject&&(!m.id||m.id===state.currentRequest)){const reject=recognitionReject;recognitionResolve=recognitionReject=null;reject(Error(m.message||'OCR error'))}};worker.postMessage({type:'SET_POWER_SAVE',enabled:state.powerSave});return worker;}
function recognize(blob){const id=crypto.randomUUID();state.currentRequest=id;recognitionProgress=0;return new Promise((resolve,reject)=>{recognitionResolve=resolve;recognitionReject=reject;ensureWorker().postMessage({type:'RECOGNIZE',id,blob})});}
function updateScanProgress(v,detail){els.scanProgress.style.width=`${Math.round(Math.max(.04,Math.min(.99,v||0))*100)}%`;if(detail)els.scanDetail.textContent=detail;}
function setScanning(on){state.scanning=on;hide(els.scanFrame,!on);hide(els.scanStatus,!on);els.selection.style.pointerEvents=on?'none':'auto';if(on){els.scanTitle.textContent=locale(state.explainLanguage,'recognizing');els.scanDetail.textContent=locale(state.explainLanguage,'recognizeDetail');updateScanProgress(.04);}}
async function analyzeSelection(){const r=state.selectionRect;if(!r||r.width<36||r.height<28)return;setScanning(true);hide(els.hint,true);try{const blob=await cropSelection(r);let o=null;try{o=await recognize(blob)}catch(e){console.warn('OCR',e)}const raw=String(o?.text||'').trim();updateScanProgress(.99,raw?'計算パターンを比較中':'認識を再確認中');state.latestRaw=raw;state.latestAnalysis=analyzeMath(raw,state.explainLanguage);state.stage='result';await sleep(150);renderAnalysis(state.latestAnalysis);hide(els.result,false);}catch(e){console.error(e);state.latestRaw='';state.latestAnalysis=analyzeMath('',state.explainLanguage);state.stage='result';renderAnalysis(state.latestAnalysis);hide(els.result,false);}finally{setScanning(false)}}

function normalizeMath(input){let s=String(input||'').trim().replace(/\$+/g,'').replace(/\\left|\\right/g,'').replace(/\\,/g,'');const map={'０':'0','１':'1','２':'2','３':'3','４':'4','５':'5','６':'6','７':'7','８':'8','９':'9','＋':'+','－':'-','−':'-','–':'-','—':'-','×':'*','✕':'*','∙':'*','⋅':'*','・':'*','÷':'/','／':'/','＝':'=','（':'(','）':')','［':'(','］':')','｛':'(','｝':')','＾':'^','％':'%'};s=[...s].map(c=>map[c]??c).join('').replace(/\\times|\\cdot/g,'*').replace(/\\div/g,'/').replace(/\\pm/g,'±');for(let i=0;i<5;i++)s=s.replace(/\\frac\s*\{([^{}]+)\}\s*\{([^{}]+)\}/g,'(($1)/($2))');s=s.replace(/\\sqrt\s*\{([^{}]+)\}/g,'sqrt($1)').replace(/√\s*([0-9.]+)/g,'sqrt($1)').replace(/\^\s*\{([^{}]+)\}/g,'^($1)').replace(/[{}]/g,m=>m==='{'?'(':')');const sup={'⁰':'0','¹':'1','²':'2','³':'3','⁴':'4','⁵':'5','⁶':'6','⁷':'7','⁸':'8','⁹':'9'};s=s.replace(/[⁰¹²³⁴⁵⁶⁷⁸⁹]+/g,m=>'^'+[...m].map(x=>sup[x]).join('')).replace(/([0-9.]+)\s*%/g,'($1/100)').replace(/[;,，]/g,'').replace(/\s+/g,'').replace(/\.{3,}/g,'').replace(/(?<=\d)[oO](?=\d|$)/g,'0').replace(/(?<=\d)[lI](?=\d|$)/g,'1').replace(/^\(+|\)+$/g,m=>m);return s;}
function generateCandidates(raw){const base=normalizeMath(raw),map=new Map(),add=(s,p=0,n='OCR')=>{s=normalizeMath(s);if(!s||s.length>220)return;const prev=map.get(s);if(!prev||p<prev.penalty)map.set(s,{text:s,penalty:p,note:n})};add(base,0,'OCR');if(!base)return[];add(base.replace(/(?<=\d)[xX](?=\d|\()/g,'*').replace(/(?<=\))[xX](?=\d|\()/g,'*'),.04,'x → ×');add(base.replace(/:/g,'/'),.06,': → ÷');add(base.replace(/(?<=\d)[oO]/g,'0').replace(/[oO](?=\d)/g,'0'),.06,'O → 0');add(base.replace(/(?<=\d)[sS](?=\d|$)/g,'5'),.1,'S → 5');add(base.replace(/(?<=\d)[bB](?=\d|$)/g,'8'),.1,'B → 8');add(base.replace(/\|/g,'1'),.08,'| → 1');add(base.replace(/[zZ](?=\d|[+\-*/=]|$)/g,'2'),.11,'Z → 2');return[...map.values()].slice(0,14)}
function tokenize(s){const a=[];let i=0;while(i<s.length){const c=s[i];if(/\s/.test(c)){i++;continue}if(/[\d.]/.test(c)){let j=i+1;while(j<s.length&&/[\d.]/.test(s[j]))j++;const raw=s.slice(i,j);if((raw.match(/\./g)||[]).length>1)throw Error('number');a.push({type:'number',value:Number(raw)});i=j;continue}if(/[A-Za-zπ]/.test(c)){let j=i+1;while(j<s.length&&/[A-Za-z0-9_π]/.test(s[j]))j++;a.push({type:'id',value:s.slice(i,j)});i=j;continue}if('+-*/^()=!,'.includes(c)){a.push({type:'op',value:c});i++;continue}throw Error('token')}
  const out=[];for(const tok of a){const prev=out.at(-1),prevEnd=prev&&(prev.type==='number'||prev.type==='id'||prev.value===')'||prev.value==='!'),nextStart=tok.type==='number'||tok.type==='id'||tok.value==='(',fn=prev?.type==='id'&&tok.value==='('&&['sqrt','sin','cos','tan','log','ln','abs'].includes(prev.value.toLowerCase());if(prevEnd&&nextStart&&!fn)out.push({type:'op',value:'*'});out.push(tok)}return out}
function parseExpressionString(s){const a=tokenize(s);let p=0;const peek=()=>a[p],take=v=>{const x=a[p];if(!x||(v&&x.value!==v))throw Error('parse');p++;return x};function primary(){const x=peek();if(!x)throw Error('primary');if(x.type==='number'){take();return{type:'num',value:x.value}}if(x.type==='id'){take();const n=x.value;if(peek()?.value==='('&&['sqrt','sin','cos','tan','log','ln','abs'].includes(n.toLowerCase())){take('(');const z=expr();take(')');return{type:'fn',name:n.toLowerCase(),arg:z}}return{type:'var',name:n}}if(x.value==='('){take('(');const n=expr();take(')');return n}throw Error('primary')}function postfix(){let n=primary();while(peek()?.value==='!'){take('!');n={type:'fact',arg:n}}return n}function unary(){if(peek()?.value==='+'||peek()?.value==='-'){const op=take().value;return{type:'unary',op,arg:unary()}}return postfix()}function power(){let l=unary();if(peek()?.value==='^'){take('^');l={type:'bin',op:'^',left:l,right:power()}}return l}function mul(){let l=power();while(peek()?.value==='*'||peek()?.value==='/'){const op=take().value;l={type:'bin',op,left:l,right:power()}}return l}function expr(){let l=mul();while(peek()?.value==='+'||peek()?.value==='-'){const op=take().value;l={type:'bin',op,left:l,right:mul()}}return l}const n=expr();if(p!==a.length)throw Error('tail');return n}
function factorial(n){if(!Number.isInteger(n)||n<0||n>170)throw Error('fact');let r=1;for(let i=2;i<=n;i++)r*=i;return r}
function evalAst(n,vars={}){if(n.type==='num')return n.value;if(n.type==='var'){const k=n.name.toLowerCase();if(k==='π'||k==='pi')return Math.PI;if(k==='e')return Math.E;if(n.name in vars)return vars[n.name];throw Error('var')}if(n.type==='unary')return n.op==='-'?-evalAst(n.arg,vars):evalAst(n.arg,vars);if(n.type==='fact')return factorial(evalAst(n.arg,vars));if(n.type==='fn'){const x=evalAst(n.arg,vars),fn={sqrt:Math.sqrt,sin:Math.sin,cos:Math.cos,tan:Math.tan,log:Math.log10,ln:Math.log,abs:Math.abs}[n.name];return fn(x)}if(n.type==='bin'){const a=evalAst(n.left,vars),b=evalAst(n.right,vars);return n.op==='+'?a+b:n.op==='-'?a-b:n.op==='*'?a*b:n.op==='/'?a/b:a**b}throw Error('eval')}
function astToString(n){if(n.type==='num')return fmt(n.value);if(n.type==='var')return n.name;if(n.type==='unary')return n.op+astToString(n.arg);if(n.type==='fact')return astToString(n.arg)+'!';if(n.type==='fn')return`${n.name}(${astToString(n.arg)})`;return`(${astToString(n.left)} ${n.op==='*'?'×':n.op==='/'?'÷':n.op} ${astToString(n.right)})`}
function collectVars(n,set=new Set()){if(n.type==='var'&&!['e','pi','π'].includes(n.name.toLowerCase()))set.add(n.name);if(n.arg)collectVars(n.arg,set);if(n.left)collectVars(n.left,set);if(n.right)collectVars(n.right,set);return set}
function poly(n,x){if(n.type==='num')return[n.value,0,0];if(n.type==='var'){if(n.name===x)return[0,1,0];if(['e','pi','π'].includes(n.name.toLowerCase()))return[evalAst(n),0,0];throw Error('var')}if(n.type==='unary'){const p=poly(n.arg,x);return n.op==='-'?p.map(v=>-v):p}if(n.type==='bin'){const a=poly(n.left,x),b=poly(n.right,x);if(n.op==='+')return a.map((v,i)=>v+b[i]);if(n.op==='-')return a.map((v,i)=>v-b[i]);if(n.op==='*'){const o=[0,0,0,0,0];for(let i=0;i<3;i++)for(let j=0;j<3;j++)o[i+j]+=a[i]*b[j];if(Math.abs(o[3])+Math.abs(o[4])>1e-10)throw Error('degree');return o.slice(0,3)}if(n.op==='/'){if(Math.abs(b[1])+Math.abs(b[2])>1e-12||Math.abs(b[0])<1e-14)throw Error('division');return a.map(v=>v/b[0])}if(n.op==='^'){const e=evalAst(n.right);if(e===0)return[1,0,0];if(e===1)return a;if(e===2){const o=[a[0]*a[0],2*a[0]*a[1],a[1]*a[1]+2*a[0]*a[2]];if(Math.abs(a[2]*a[2])+Math.abs(a[1]*a[2])>1e-12)throw Error('degree');return o}throw Error('power')}}throw Error('poly')}
function arithmeticSteps(ast,s,lang){const steps=[locale(lang,'normalized',s)];function walk(n){if(n.type==='num')return n.value;if(n.type==='bin'){const a=walk(n.left),b=walk(n.right);if(Number.isFinite(a)&&Number.isFinite(b)){const v=evalAst({type:'bin',op:n.op,left:{type:'num',value:a},right:{type:'num',value:b}});steps.push(`${fmt(a)} ${n.op==='*'?'×':n.op==='/'?'÷':n.op} ${fmt(b)} = ${fmt(v)}`);return v}}try{const v=evalAst(n);steps.push(`${astToString(n)} = ${fmt(v)}`);return v}catch{return NaN}}const v=walk(ast);if(Number.isFinite(v))steps.push(locale(lang,'result',fmt(v)));return steps}
function formatPoly(a,b,c,x){const parts=[];if(Math.abs(a)>1e-12)parts.push(`${fmt(a)}${x}²`);if(Math.abs(b)>1e-12)parts.push(`${b>=0&&parts.length?'+ ':b<0?'− ':''}${fmt(Math.abs(b))}${x}`);if(Math.abs(c)>1e-12||!parts.length)parts.push(`${c>=0&&parts.length?'+ ':c<0?'− ':''}${fmt(Math.abs(c))}`);return parts.join(' ')}
function solveCandidate(s,lang){const parts=s.split('=');if(parts.length>2)throw Error('eq');if(parts.length===2){const l=parseExpressionString(parts[0]),r=parseExpressionString(parts[1]),vars=[...new Set([...collectVars(l),...collectVars(r)])];if(!vars.length){const a=evalAst(l),b=evalAst(r),ok=Math.abs(a-b)<1e-10;return{normalized:s,answer:ok?'✓':'≠',steps:[locale(lang,'normalized',s),locale(lang,'comparison'),`${fmt(a)} ${ok?'=':'≠'} ${fmt(b)}`],kind:'comparison'}}if(vars.length>1)throw Error('many vars');const x=vars[0],lp=poly(l,x),rp=poly(r,x),p=lp.map((v,i)=>v-rp[i]),[c,b,a]=p;if(Math.abs(a)<1e-10&&Math.abs(b)<1e-10){const identity=Math.abs(c)<1e-10;return{normalized:s,answer:locale(lang,identity?'identity':'noSolution'),steps:[locale(lang,'normalized',s),locale(lang,'move'),`${fmt(c)} = 0`],kind:'equation'}}if(Math.abs(a)<1e-10){const ans=-c/b;return{normalized:s,answer:`${x} = ${fmt(ans)}`,steps:[locale(lang,'normalized',s),locale(lang,'move'),`${fmt(b)}${x} ${c>=0?'+':'−'} ${fmt(Math.abs(c))} = 0`,`${fmt(b)}${x} = ${fmt(-c)}`,locale(lang,'divide',b),`${x} = ${fmt(ans)}`],kind:'linear'}}const d=b*b-4*a*c,steps=[locale(lang,'normalized',s),locale(lang,'move'),`${formatPoly(a,b,c,x)} = 0`,locale(lang,'discriminant',d),locale(lang,'quadratic')];if(d<0){steps.push(locale(lang,'noReal'));return{normalized:s,answer:locale(lang,'noReal'),steps,kind:'quadratic'}}const q=Math.sqrt(d),x1=(-b+q)/(2*a),x2=(-b-q)/(2*a),ans=Math.abs(x1-x2)<1e-10?`${x} = ${fmt(x1)}`:`${x} = ${fmt(x1)}, ${fmt(x2)}`;steps.push(ans);return{normalized:s,answer:ans,steps,kind:'quadratic'}}
  const ast=parseExpressionString(s),vars=[...collectVars(ast)];if(!vars.length){const v=evalAst(ast);if(!Number.isFinite(v))throw Error('nonfinite');return{normalized:s,answer:fmt(v),steps:arithmeticSteps(ast,s,lang),kind:'arithmetic'}}if(vars.length===1){const p=poly(ast,vars[0]);const simp=formatPoly(p[2],p[1],p[0],vars[0]);return{normalized:s,answer:simp,steps:[locale(lang,'normalized',s),locale(lang,'simplify'),simp],kind:'symbolic'}}throw Error('vars')}
function analyzeMath(raw,lang='ja'){const solved=[];generateCandidates(raw).forEach((c,i)=>{try{const s=solveCandidate(c.text,lang);let score=1-c.penalty-i*.005;if(['arithmetic','linear','quadratic'].includes(s.kind))score+=.24;if(s.normalized.includes('='))score+=.04;if(s.steps.length>=2)score+=.03;solved.push({...s,score,note:c.note})}catch{}});solved.sort((a,b)=>b.score-a.score);if(!solved.length)return{raw,best:{normalized:normalizeMath(raw),answer:locale(lang,'noFormula'),steps:[locale(lang,'retry')],score:0,note:'retry'},alternatives:[]};return{raw,best:solved[0],alternatives:solved.slice(1,6)}}
function renderAnalysis(a){const b=a.best,lang=state.explainLanguage;els.resultValue.textContent=b.answer;els.recognizedFormula.textContent=b.normalized||a.raw||'—';els.stepsTitle.textContent=locale(lang,'steps');els.alternativesTitle.textContent=locale(lang,'alts');els.stepsList.replaceChildren(...b.steps.map(s=>{const li=document.createElement('li');li.textContent=s;return li}));els.stepCounter.textContent=locale(lang,'stepCount',b.steps.length);const alts=a.alternatives||[];els.alternativeCount.textContent=locale(lang,'altCount',alts.length);els.alternativeCards.replaceChildren(...alts.map((x,i)=>{const e=document.createElement('button');e.type='button';e.className='alt-card';const code=document.createElement('code'),strong=document.createElement('strong'),small=document.createElement('small');code.textContent=x.normalized;strong.textContent=x.answer;small.textContent=`#${i+2} · ${x.note||'candidate'}`;e.append(code,strong,small);e.onclick=()=>{state.latestRaw=x.normalized;state.latestAnalysis=analyzeMath(x.normalized,state.explainLanguage);renderAnalysis(state.latestAnalysis)};return e}));hide(els.alternativesPanel,!state.alternativesOpen||!alts.length);els.alternativesButton.disabled=!alts.length;els.alternativesButton.style.opacity=alts.length?'1':'.42';els.alternativesButton.textContent=state.alternativesOpen?locale(lang,'hideAlts'):locale(lang,'showAlts')}
function backOneLevel(){if(state.stage==='result'){state.stage='select';state.alternativesOpen=false;hide(els.result,true);hide(els.alternativesPanel,true);state.selectionRect=null;state.latestRaw='';state.latestAnalysis=null;drawSelection();hide(els.hint,false);return}if(state.stage==='select'){state.stage='camera';state.selectionRect=null;state.latestRaw='';state.latestAnalysis=null;hide(els.photoStage,true);hide(els.result,true);hide(els.cameraStage,false);startCamera()}}

function extractExpression(text){let s=String(text||'').trim().replace(/計算して|計算|解いて|求めて|答え|は何|いくつ|solve|calculate|what is|please/gi,'');s=normalizeMath(s);const direct=s.replace(/[^0-9A-Za-zπ+\-*/^()=!.]/g,'');if(direct&&/[0-9π)]/.test(direct)&&/[+\-*/=^!]/.test(direct))return direct;const matches=String(text).match(/[0-9０-９A-Za-zπ√（(][0-9０-９A-Za-zπ√＋+－−\-×*÷/^()（）=＝.!\s]{2,}/g)||[];return normalizeMath(matches.sort((a,b)=>b.length-a.length)[0]||'')}
function addChatMessage(role,text,analysis=null){const box=document.createElement('div');box.className=`message ${role}`;if(analysis){const ans=document.createElement('span');ans.className='answer';ans.textContent=analysis.best.answer;box.append(ans);const code=document.createElement('code');code.textContent=analysis.best.normalized||text;box.append(code);const ol=document.createElement('ol');analysis.best.steps.forEach(s=>{const li=document.createElement('li');li.textContent=s;ol.append(li)});box.append(ol)}else{const p=document.createElement('p');p.textContent=text;box.append(p)}els.chatMessages.append(box);els.chatMessages.scrollTop=els.chatMessages.scrollHeight;}
function openChat(){if(state.chatOpen)return;state.chatOpen=true;if(state.stage==='camera')stopCamera();hide(els.chatPanel,false);requestAnimationFrame(()=>els.chatInput.focus())}
function closeChat(){if(!state.chatOpen)return;state.chatOpen=false;hide(els.chatPanel,true);if(state.stage==='camera')startCamera()}
function renderChatLanguageHint(){els.chatInput.placeholder=state.explainLanguage==='en'?'Enter a calculation…':'計算式を入力…'}
function submitChat(){const text=els.chatInput.value.trim();if(!text)return;addChatMessage('user',text);els.chatInput.value='';const expr=extractExpression(text),analysis=analyzeMath(expr,state.explainLanguage);if(!expr||analysis.best.score===0)addChatMessage('assistant',locale(state.explainLanguage,'chatFail'));else addChatMessage('assistant','',analysis)}

els.shutter.onclick=capture;els.back.onclick=backOneLevel;els.resultClose.onclick=backOneLevel;els.powerSave.onchange=e=>setPowerSave(e.target.checked);els.explainLanguage.onchange=e=>setExplainLanguage(e.target.checked?'en':'ja');els.chatLanguage.onchange=e=>setExplainLanguage(e.target.checked?'en':'ja');els.alternativesButton.onclick=()=>{state.alternativesOpen=!state.alternativesOpen;hide(els.alternativesPanel,!state.alternativesOpen);els.alternativesButton.textContent=state.alternativesOpen?locale(state.explainLanguage,'hideAlts'):locale(state.explainLanguage,'showAlts')};els.chatOpen.onclick=openChat;els.chatClose.onclick=closeChat;els.chatForm.onsubmit=e=>{e.preventDefault();submitChat()};els.chatInput.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submitChat()}});
els.selection.onpointerdown=e=>{if(state.scanning||state.stage!=='select')return;els.selection.setPointerCapture(e.pointerId);state.dragStart=pointerPoint(e);state.selectionRect={x:state.dragStart.x,y:state.dragStart.y,width:0,height:0};drawSelection();hide(els.hint,true)};els.selection.onpointermove=e=>{if(state.dragStart&&!state.scanning){state.selectionRect=makeRect(state.dragStart,pointerPoint(e));drawSelection()}};els.selection.onpointerup=e=>{if(!state.dragStart||state.scanning)return;state.selectionRect=makeRect(state.dragStart,pointerPoint(e));state.dragStart=null;drawSelection();if(state.selectionRect.width>=36&&state.selectionRect.height>=28)analyzeSelection();else hide(els.hint,false)};
addEventListener('resize',()=>{if(state.stage!=='camera'){resizeSelectionCanvas();drawSelection()}});document.addEventListener('visibilitychange',()=>{if(document.hidden)stopCamera();else if(!state.chatOpen&&state.stage==='camera')startCamera()});
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));
els.powerSave.checked=state.powerSave;els.app.classList.toggle('power-save',state.powerSave);els.explainLanguage.checked=state.explainLanguage==='en';els.chatLanguage.checked=state.explainLanguage==='en';renderChatLanguageHint();startCamera();setTimeout(()=>{ensureWorker().postMessage({type:'SET_POWER_SAVE',enabled:state.powerSave});if(!state.powerSave)ensureWorker().postMessage({type:'WARMUP'})},1800);
