const $=id=>document.getElementById(id);
const els={
  app:$('app'),cameraScene:$('cameraScene'),camera:$('camera'),cameraError:$('cameraError'),chatOpen:$('chatOpen'),settingsOpen:$('settingsOpen'),engineStatus:$('engineStatus'),eco:$('ecoSwitch'),eco2:$('ecoSwitch2'),accuracy:$('accuracySwitch'),diagnostic:$('diagnosticSwitch'),modeDock:$('modeDock'),gallery:$('galleryInput'),shutter:$('shutter'),
  photoScene:$('photoScene'),photo:$('photo'),photoBlur:$('photoBlur'),selection:$('selectionCanvas'),photoBack:$('photoBack'),newPhoto:$('newPhoto'),photoMode:$('photoMode'),selectionHint:$('selectionHint'),crop:$('cropCanvas'),
  aurora:$('aurora'),processing:$('processing'),processingTitle:$('processingTitle'),processingDetail:$('processingDetail'),progress:$('progressBar'),
  result:$('resultCard'),resultBadge:$('resultBadge'),resultTitle:$('resultTitle'),resultMeta:$('resultMeta'),resultClose:$('resultClose'),answerBlock:$('answerBlock'),answerValue:$('answerValue'),answerSub:$('answerSub'),editableBlock:$('editableBlock'),editableLabel:$('editableLabel'),editableText:$('editableText'),applyEdit:$('applyEdit'),retryRead:$('retryRead'),translationBlock:$('translationBlock'),translationFrom:$('translationFrom'),translationTo:$('translationTo'),colorBlock:$('colorBlock'),colorSwatch:$('colorSwatch'),colorHex:$('colorHex'),colorRgb:$('colorRgb'),colorHsl:$('colorHsl'),steps:$('stepsSection'),stepCount:$('stepCount'),stepsList:$('stepsList'),candidates:$('candidateSection'),candidateCount:$('candidateCount'),candidateList:$('candidateList'),copy:$('copyAction'),speak:$('speakAction'),more:$('moreAction'),
  chatPanel:$('chatPanel'),chatClose:$('chatClose'),chatMessages:$('chatMessages'),chatForm:$('chatForm'),chatInput:$('chatInput'),settingsPanel:$('settingsPanel'),settingsClose:$('settingsClose'),storageInfo:$('storageInfo')
};

const state={
  scene:'camera',mode:localStorage.getItem('lens-mode')||'smart',stream:null,photoUrl:'',naturalWidth:0,naturalHeight:0,selectionRect:null,dragStart:null,processing:false,
  eco:localStorage.getItem('lens-eco')==='1',accuracy:localStorage.getItem('lens-accuracy')!=='0',diagnostic:localStorage.getItem('lens-diagnostic')==='1',
  latest:null,progress:0,chatOpen:false,settingsOpen:false
};

let tessPromise=null,paddlePromise=null,mathWorker=null,mathResolve=null,mathReject=null,mathRequest=null,utilityWorker=null,translationResolve=null,translationReject=null;
const hide=(el,yes)=>el?.classList.toggle('hidden',!!yes);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const fmt=n=>{if(!Number.isFinite(n))return String(n);if(Math.abs(n)<1e-12)n=0;return Number.isInteger(n)?String(n):String(Number(n.toPrecision(10)))};
const modes={smart:{label:'スマート',hint:'調べたい範囲を囲む'},math:{label:'解く',hint:'数式だけを囲む'},text:{label:'文字',hint:'読みたい文字を囲む'},translate:{label:'翻訳',hint:'翻訳したい文を囲む'},color:{label:'色',hint:'色を調べたい部分を囲む'}};

function setMode(mode){if(!modes[mode])return;state.mode=mode;localStorage.setItem('lens-mode',mode);document.querySelectorAll('.mode').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));els.photoMode.textContent=modes[mode].label;els.selectionHint.textContent=modes[mode].hint}
function setEco(v){state.eco=!!v;localStorage.setItem('lens-eco',v?'1':'0');els.eco.checked=state.eco;els.eco2.checked=state.eco;els.app.classList.toggle('eco-mode',state.eco);if(state.scene==='camera'&&!state.chatOpen&&!state.settingsOpen)startCamera()}
function setAccuracy(v){state.accuracy=!!v;localStorage.setItem('lens-accuracy',v?'1':'0');els.accuracy.checked=state.accuracy}
function setDiagnostic(v){state.diagnostic=!!v;localStorage.setItem('lens-diagnostic',v?'1':'0');els.diagnostic.checked=state.diagnostic}

async function startCamera(){stopCamera();hide(els.cameraError,true);if(state.chatOpen||state.settingsOpen)return;try{const q=state.eco?{width:{ideal:1280},height:{ideal:720},frameRate:{ideal:24,max:30}}:{width:{ideal:3840},height:{ideal:2160},frameRate:{ideal:30,max:30}};state.stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},...q}});els.camera.srcObject=state.stream;await els.camera.play();els.engineStatus.textContent=state.eco?'ECO · LOCAL':'LOCAL'}catch(e){els.cameraError.textContent='カメラを開始できません。ブラウザのカメラ権限を確認してください。';hide(els.cameraError,false)}}
function stopCamera(){state.stream?.getTracks().forEach(t=>t.stop());state.stream=null;els.camera.srcObject=null}

async function useBlobAsPhoto(blob){if(!blob)return;if(state.photoUrl)URL.revokeObjectURL(state.photoUrl);state.photoUrl=URL.createObjectURL(blob);els.photo.src=state.photoUrl;await els.photo.decode().catch(()=>{});state.naturalWidth=els.photo.naturalWidth;state.naturalHeight=els.photo.naturalHeight;els.photoBlur.style.backgroundImage=`url("${state.photoUrl}")`;state.selectionRect=null;state.latest=null;state.scene='photo';stopCamera();hide(els.cameraScene,true);hide(els.photoScene,false);hide(els.result,true);hide(els.processing,true);hide(els.aurora,true);hide(els.selectionHint,false);els.photoMode.textContent=modes[state.mode].label;els.selectionHint.textContent=modes[state.mode].hint;resizeSelection();drawSelection()}
async function capture(){if(!els.camera.videoWidth)return;const c=document.createElement('canvas');c.width=els.camera.videoWidth;c.height=els.camera.videoHeight;c.getContext('2d',{alpha:false}).drawImage(els.camera,0,0,c.width,c.height);const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',state.eco?.92:.985));await useBlobAsPhoto(blob)}

function fitImage(){const cw=innerWidth,ch=innerHeight,iw=state.naturalWidth||cw,ih=state.naturalHeight||ch,scale=Math.min(cw/iw,ch/ih),width=iw*scale,height=ih*scale;return{x:(cw-width)/2,y:(ch-height)/2,width,height,scale}}
function resizeSelection(){const r=els.selection.getBoundingClientRect(),dpr=Math.max(1,devicePixelRatio||1),w=Math.max(1,Math.round(r.width*dpr)),h=Math.max(1,Math.round(r.height*dpr));if(els.selection.width!==w||els.selection.height!==h){els.selection.width=w;els.selection.height=h}}
const point=e=>{const r=els.selection.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};
const rectFrom=(a,b)=>({x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),width:Math.abs(a.x-b.x),height:Math.abs(a.y-b.y)});
function drawSelection(){resizeSelection();const ctx=els.selection.getContext('2d'),dpr=els.selection.width/Math.max(1,els.selection.clientWidth),r=state.selectionRect;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,els.selection.clientWidth,els.selection.clientHeight);if(!r)return;ctx.fillStyle='rgba(0,0,0,.34)';ctx.fillRect(0,0,els.selection.clientWidth,els.selection.clientHeight);ctx.clearRect(r.x,r.y,r.width,r.height);const g=ctx.createLinearGradient(r.x,r.y,r.x+r.width,r.y+r.height);['#4285f4','#a142f4','#ea4335','#fbbc04','#34a853'].forEach((c,i,a)=>g.addColorStop(i/(a.length-1),c));ctx.strokeStyle=g;ctx.lineWidth=3;ctx.setLineDash([11,7]);ctx.strokeRect(r.x+1.5,r.y+1.5,Math.max(0,r.width-3),Math.max(0,r.height-3))}
function sourceRect(r){const f=fitImage(),l=Math.max(r.x,f.x),t=Math.max(r.y,f.y),rr=Math.min(r.x+r.width,f.x+f.width),bb=Math.min(r.y+r.height,f.y+f.height);if(rr-l<12||bb-t<12)throw Error('範囲が小さすぎます');return{sx:(l-f.x)/f.scale,sy:(t-f.y)/f.scale,sw:(rr-l)/f.scale,sh:(bb-t)/f.scale}}
async function cropSelection(r,{math=false}={}){let{sx,sy,sw,sh}=sourceRect(r);const px=sw*(math?.12:.05),py=sh*(math?.22:.08);sx-=px;sy-=py;sw+=px*2;sh+=py*2;sx=Math.max(0,sx);sy=Math.max(0,sy);sw=Math.min(state.naturalWidth-sx,sw);sh=Math.min(state.naturalHeight-sy,sh);const maxSide=state.eco?1200:2300,scale=Math.min(3,maxSide/Math.max(sw,sh)),c=els.crop;c.width=Math.max(160,Math.round(sw*scale));c.height=Math.max(96,Math.round(sh*scale));const ctx=c.getContext('2d',{alpha:false});ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.filter=math?'grayscale(1) contrast(1.2) brightness(1.04)':'contrast(1.08) brightness(1.03)';ctx.drawImage(els.photo,sx,sy,sw,sh,0,0,c.width,c.height);ctx.filter='none';return new Promise(res=>c.toBlob(res,'image/png'))}

function setProcessing(on,title='解析中',detail='画像を確認しています'){state.processing=on;hide(els.aurora,!on);hide(els.processing,!on);els.selection.style.pointerEvents=on?'none':'auto';if(on){state.progress=.03;els.processingTitle.textContent=title;els.processingDetail.textContent=detail;els.progress.style.width='3%'}}
function progress(v,detail){state.progress=Math.max(state.progress,Number(v)||0);els.progress.style.width=`${Math.round(Math.min(.99,Math.max(.03,state.progress))*100)}%`;if(detail)els.processingDetail.textContent=detail}

async function makeVariants(blob){const out=[{name:'original',blob}];if(typeof createImageBitmap==='undefined')return out;const bm=await createImageBitmap(blob);try{const scale=Math.min(2.4,1800/Math.max(bm.width,bm.height)),w=Math.max(180,Math.round(bm.width*scale)),h=Math.max(100,Math.round(bm.height*scale)),base=document.createElement('canvas');base.width=w;base.height=h;const b=base.getContext('2d',{willReadFrequently:true});b.fillStyle='#fff';b.fillRect(0,0,w,h);b.drawImage(bm,0,0,w,h);const img=b.getImageData(0,0,w,h),gray=new Uint8Array(w*h),hist=new Uint32Array(256);for(let i=0;i<gray.length;i++){const v=Math.round(.299*img.data[i*4]+.587*img.data[i*4+1]+.114*img.data[i*4+2]);gray[i]=v;hist[v]++}let total=gray.length,sum=0;for(let i=0;i<256;i++)sum+=i*hist[i];let sb=0,wb=0,max=0,thr=160;for(let i=0;i<256;i++){wb+=hist[i];if(!wb)continue;const wf=total-wb;if(!wf)break;sb+=i*hist[i];const mb=sb/wb,mf=(sum-sb)/wf,v=wb*wf*(mb-mf)*(mb-mf);if(v>max){max=v;thr=i}}for(const [name,kind] of [['contrast',0],['binary',1]]){const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d'),d=ctx.createImageData(w,h);for(let i=0;i<gray.length;i++){let v=kind?(gray[i]<Math.min(215,thr+10)?0:255):Math.max(0,Math.min(255,(gray[i]-128)*2+145));d.data[i*4]=d.data[i*4+1]=d.data[i*4+2]=v;d.data[i*4+3]=255}ctx.putImageData(d,0,0);out.push({name,blob:await new Promise(r=>c.toBlob(r,'image/png'))})}}finally{bm.close?.()}return out.filter(x=>x.blob)}
