async function analyzeSelection(){const r=state.selectionRect;if(!r||r.width<24||r.height<18)return;setProcessing(true,'解析中','選択範囲を確認しています');hide(els.selectionHint,true);try{if(state.mode==='color'){renderColor(sampleColor(r));return}const textBlob=await cropSelection(r,{math:false}),mathBlob=await cropSelection(r,{math:true});if(state.mode==='math'){renderMath(await recognizeMath(mathBlob));return}if(state.mode==='text'){renderText(await recognizeText(textBlob));return}if(state.mode==='translate'){const t=await recognizeText(textBlob);if(!t.best.text){renderText(t);return}await translateText(t.best.text);return}progress(.1,'内容の種類を判定中');const [shape,text]=await Promise.all([shapeMath(mathBlob),recognizeText(textBlob)]);const textLooksMath=mathLike(text.best.text),shapeLooksMath=shape.some(x=>mathLike(x.text));if(textLooksMath||shapeLooksMath){const math=await recognizeMath(mathBlob);if(math.best){renderMath(math);return}}renderText(text)}catch(e){console.error(e);resetResult();els.resultBadge.textContent='ERROR';els.resultTitle.textContent='処理できませんでした';els.resultMeta.textContent=String(e?.message||e);hide(els.editableBlock,false);els.editableLabel.textContent='手入力';els.editableText.value='';els.applyEdit.textContent='計算';els.applyEdit.onclick=()=>renderMath(analyze([{text:els.editableText.value,source:'manual',confidence:1}]));els.retryRead.onclick=()=>rerunCurrent();hide(els.result,false)}finally{setProcessing(false)}}
async function rerunCurrent(){hide(els.result,true);await analyzeSelection()}

function backToCamera(){state.scene='camera';state.selectionRect=null;hide(els.result,true);hide(els.photoScene,true);hide(els.cameraScene,false);startCamera()}
function backFromResult(){hide(els.result,true);state.scene='photo';state.selectionRect=null;drawSelection();hide(els.selectionHint,false)}

function addChat(role,text,analysis=null){const d=document.createElement('div');d.className=`bubble ${role}`;if(analysis?.best){d.innerHTML=`<b>${escapeHtml(analysis.best.answer)}</b><br><code>${escapeHtml(analysis.best.expression)}</code><br>${analysis.best.steps.map(x=>escapeHtml(x)).join('<br>')}`}else d.textContent=text;els.chatMessages.append(d);els.chatMessages.scrollTop=els.chatMessages.scrollHeight}
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function openChat(){state.chatOpen=true;stopCamera();hide(els.chatPanel,false);requestAnimationFrame(()=>els.chatInput.focus())}
function closeChat(){state.chatOpen=false;hide(els.chatPanel,true);if(state.scene==='camera')startCamera()}
function openSettings(){state.settingsOpen=true;stopCamera();hide(els.settingsPanel,false)}
function closeSettings(){state.settingsOpen=false;hide(els.settingsPanel,true);if(state.scene==='camera')startCamera()}
function submitChat(){const t=els.chatInput.value.trim();if(!t)return;addChat('user',t);els.chatInput.value='';if(/^文字数[:：]?/i.test(t)){const body=t.replace(/^文字数[:：]?/i,'').trim();addChat('assistant',`${body.length}文字`);return}const a=analyze([{text:t,source:'chat',confidence:1}]);if(a.best)addChat('assistant','',a);else addChat('assistant','式として計算できませんでした。')}

els.shutter.onclick=capture;els.gallery.onchange=e=>{const f=e.target.files?.[0];if(f)useBlobAsPhoto(f);e.target.value=''};els.modeDock.onclick=e=>{const b=e.target.closest('.mode');if(b)setMode(b.dataset.mode)};els.eco.onchange=e=>setEco(e.target.checked);els.eco2.onchange=e=>setEco(e.target.checked);els.accuracy.onchange=e=>setAccuracy(e.target.checked);els.diagnostic.onchange=e=>setDiagnostic(e.target.checked);els.photoBack.onclick=backToCamera;els.newPhoto.onclick=backToCamera;els.resultClose.onclick=backFromResult;els.chatOpen.onclick=openChat;els.chatClose.onclick=closeChat;els.settingsOpen.onclick=openSettings;els.settingsClose.onclick=closeSettings;els.chatForm.onsubmit=e=>{e.preventDefault();submitChat()};els.chatInput.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submitChat()}};
els.selection.onpointerdown=e=>{if(state.processing)return;els.selection.setPointerCapture(e.pointerId);state.dragStart=point(e);state.selectionRect={x:state.dragStart.x,y:state.dragStart.y,width:0,height:0};drawSelection();hide(els.selectionHint,true)};els.selection.onpointermove=e=>{if(state.dragStart&&!state.processing){state.selectionRect=rectFrom(state.dragStart,point(e));drawSelection()}};els.selection.onpointerup=e=>{if(!state.dragStart||state.processing)return;state.selectionRect=rectFrom(state.dragStart,point(e));state.dragStart=null;drawSelection();if(state.selectionRect.width>=24&&state.selectionRect.height>=18)analyzeSelection();else hide(els.selectionHint,false)};
addEventListener('resize',()=>{if(state.scene!=='camera'){resizeSelection();drawSelection()}});document.addEventListener('visibilitychange',()=>{if(document.hidden)stopCamera();else if(state.scene==='camera'&&!state.chatOpen&&!state.settingsOpen)startCamera()});
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));

els.eco.checked=els.eco2.checked=state.eco;els.accuracy.checked=state.accuracy;els.diagnostic.checked=state.diagnostic;els.app.classList.toggle('eco-mode',state.eco);setMode(state.mode);startCamera();
if(navigator.storage?.estimate)navigator.storage.estimate().then(x=>{const used=x.usage?Math.round(x.usage/1024/1024):0;els.storageInfo.textContent=`ローカル保存使用量: 約${used}MB。OCR/翻訳モデルは初回利用時に保存されます。`}).catch(()=>{});
