async function ensureTesseract(){if(tessPromise)return tessPromise;tessPromise=(async()=>{progress(.08,'OCRを準備中');const mod=await import('https://cdn.jsdelivr.net/npm/tesseract.js@7/dist/tesseract.esm.min.js');return mod.createWorker(['eng','jpn'],mod.OEM?.LSTM_ONLY??1,{logger:m=>{if(typeof m?.progress==='number')progress(.18+m.progress*.45,m.status||'文字を読んでいます')}})})();try{return await tessPromise}catch(e){tessPromise=null;throw e}}
async function tesseract(blob,{math=false}={}){try{const w=await ensureTesseract();await w.setParameters(math?{tessedit_pageseg_mode:'7',tessedit_char_whitelist:'0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ+-=*/^().×÷'}:{tessedit_pageseg_mode:'6',preserve_interword_spaces:'1'});const r=await w.recognize(blob),text=String(r?.data?.text||'').trim(),confidence=(Number(r?.data?.confidence)||0)/100;return text?[{text,source:'tesseract',confidence}]:[]}catch(e){console.warn('Tesseract',e);return[]}}

async function ensurePaddle(){if(paddlePromise)return paddlePromise;paddlePromise=(async()=>{progress(.08,'高精度OCRを準備中');const mod=await import('https://esm.sh/@paddleocr/paddleocr-js@0.4.2?bundle');return mod.PaddleOCR.create({lang:'ch',ocrVersion:'PP-OCRv5',worker:false,ortOptions:{backend:'wasm',wasmPaths:'https://cdn.jsdelivr.net/npm/onnxruntime-web/dist/',numThreads:1,simd:true}})})();try{return await paddlePromise}catch(e){paddlePromise=null;throw e}}
function sortItems(items){return [...(items||[])].sort((a,b)=>{const ay=Math.min(...(a.poly||[[0,0]]).map(p=>p[1])),by=Math.min(...(b.poly||[[0,0]]).map(p=>p[1]));if(Math.abs(ay-by)>18)return ay-by;return Math.min(...(a.poly||[[0,0]]).map(p=>p[0]))-Math.min(...(b.poly||[[0,0]]).map(p=>p[0]))})}
async function paddle(blob,{math=false}={}){try{const ocr=await ensurePaddle(),vars=state.eco?[{name:'original',blob}]:await makeVariants(blob),entries=[];progress(.17,'PP-OCRv5で確認中');for(let i=0;i<vars.length;i++){try{const rr=await ocr.predict(vars[i].blob,{textDetThresh:.1,textDetBoxThresh:.12,textDetUnclipRatio:2.1,textRecScoreThresh:0}),r=rr?.[0]||rr||{},items=sortItems(r.items),text=items.map(x=>String(x.text||'')).join(math?'':'\n').trim(),confidence=items.length?items.reduce((s,x)=>s+(Number(x.score)||0),0)/items.length:0;if(text)entries.push({text,source:`paddle-${vars[i].name}`,confidence})}catch(e){console.warn('Paddle pass',e)}}return entries}catch(e){console.warn('Paddle',e);return[]}}

function ensureMathWorker(){if(mathWorker)return mathWorker;mathWorker=new Worker('./ocr-worker.js',{type:'module'});mathWorker.onmessage=e=>{const m=e.data||{};if(m.type==='progress')progress(Math.min(.9,Number(m.progress)||0),m.detail);else if(m.type==='result'&&mathResolve&&m.id===mathRequest){const r=mathResolve;mathResolve=mathReject=null;r(m)}else if(m.type==='error'&&mathReject&&m.id===mathRequest){const r=mathReject;mathResolve=mathReject=null;r(Error(m.message||'数式OCRエラー'))}};mathWorker.postMessage({type:'SET_POWER_SAVE',enabled:false});return mathWorker}
function mathModel(blob,timeout=18000){const id=crypto.randomUUID();mathRequest=id;return Promise.race([new Promise((resolve,reject)=>{mathResolve=resolve;mathReject=reject;ensureMathWorker().postMessage({type:'RECOGNIZE',id,blob})}),new Promise((_,reject)=>setTimeout(()=>reject(Error('timeout')),timeout))])}

async function shapeMath(blob){if(typeof createImageBitmap==='undefined')return[];const bm=await createImageBitmap(blob);try{const scale=Math.min(3,1100/Math.max(bm.width,bm.height)),w=Math.max(120,Math.round(bm.width*scale)),h=Math.max(70,Math.round(bm.height*scale)),c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.drawImage(bm,0,0,w,h);const d=ctx.getImageData(0,0,w,h).data,g=new Uint8Array(w*h),hist=new Uint32Array(256);for(let i=0;i<g.length;i++){const v=Math.round(.299*d[i*4]+.587*d[i*4+1]+.114*d[i*4+2]);g[i]=v;hist[v]++}let sum=0,total=g.length;for(let i=0;i<256;i++)sum+=i*hist[i];let sb=0,wb=0,best=0,t=160;for(let i=0;i<256;i++){wb+=hist[i];if(!wb)continue;const wf=total-wb;if(!wf)break;sb+=i*hist[i];const mb=sb/wb,mf=(sum-sb)/wf,v=wb*wf*(mb-mf)*(mb-mf);if(v>best){best=v;t=i}}const bin=new Uint8Array(w*h);for(let i=0;i<bin.length;i++)bin[i]=g[i]<Math.min(210,t+15)?1:0;let minX=w,minY=h,maxX=-1,maxY=-1;for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(bin[y*w+x]){minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y)}if(maxX<0)return[];const bw=maxX-minX+1,bh=maxY-minY+1,cols=new Int32Array(bw);for(let x=0;x<bw;x++)for(let y=0;y<bh;y++)if(bin[(minY+y)*w+minX+x])cols[x]++;const seg=[];let s=-1,gap=0,maxGap=Math.max(1,Math.round(bh*.028));for(let x=0;x<=bw;x++){const ink=x<bw&&cols[x]>0;if(ink){if(s<0)s=x;gap=0}else if(s>=0){gap++;if(gap>maxGap||x===bw){const e=x-gap;if(e>=s)seg.push([s,e]);s=-1;gap=0}}}let text='',score=0,n=0;for(const [a,z] of seg){let ty=bh,by=-1;for(let x=a;x<=z;x++)for(let y=0;y<bh;y++)if(bin[(minY+y)*w+minX+x]){ty=Math.min(ty,y);by=Math.max(by,y)}if(by<0)continue;const gw=z-a+1,gh=by-ty+1,rows=new Int32Array(gh),cs=new Int32Array(gw);for(let y=0;y<gh;y++)for(let x=0;x<gw;x++)if(bin[(minY+ty+y)*w+minX+a+x]){rows[y]++;cs[x]++}const rm=Math.max(...rows),cm=Math.max(...cs),ratio=gw/gh;let runs=0,on=false;for(let y=0;y<gh;y++){const strong=rows[y]/Math.max(1,gw)>.47;if(strong&&!on)runs++;on=strong}let ch='',q=0;if(runs>=2&&ratio>.8&&cm/gh<.67){ch='=';q=.96}else if(rm/gw>.48&&cm/gh>.36&&ratio>.3&&ratio<2.5){ch='+';q=.94}else if(ratio>1.25&&rm/gw>.62&&cm/gh<.33){ch='-';q=.92}else if((ratio<.52&&cm/gh>.58)||cm/gh>.8){ch='1';q=.91}else continue;text+=ch;score+=q;n++}return text?[{text,source:'shape',confidence:n?score/n:.55}]:[]}finally{bm.close?.()}}
