function resetResult(){hide(els.answerBlock,true);hide(els.editableBlock,true);hide(els.translationBlock,true);hide(els.colorBlock,true);hide(els.steps,true);hide(els.candidates,true);els.resultMeta.textContent='';els.copy.disabled=false;els.speak.disabled=false;els.more.disabled=false;els.more.textContent='候補'}
function showCandidates(items){els.candidateList.replaceChildren(...(items||[]).map((x,i)=>{const b=document.createElement('button');b.className='candidate';const strong=document.createElement('b'),span=document.createElement('span');strong.textContent=x.expression||x.text||'—';span.textContent=`${x.source||'候補'}${x.answer?' · '+x.answer:''}`;b.append(strong,span);b.onclick=()=>{if(x.expression){const a=analyze([{text:x.expression,source:'selected',confidence:1}]);renderMath(a)}else{els.editableText.value=x.text||''}};return b}));els.candidateCount.textContent=`${(items||[]).length}件`;hide(els.candidates,!(items||[]).length)}
function renderMath(a){resetResult();state.latest={type:'math',analysis:a};const b=a.best;els.resultBadge.textContent='SOLVE';els.resultTitle.textContent=b?'計算しました':'式を確定できません';els.resultMeta.textContent=b?(state.diagnostic?`${b.source} · ${Math.round((b.confidence||0)*100)}%`:'認識結果を編集できます'):'候補を確認するか、式を直接入力してください';hide(els.answerBlock,!b);if(b){els.answerValue.textContent=b.answer;els.answerSub.textContent=b.expression}hide(els.editableBlock,false);els.editableLabel.textContent='認識した式';els.editableText.value=b?.expression||a.entries?.[0]?.text||'';els.applyEdit.onclick=()=>{const next=analyze([{text:els.editableText.value,source:'manual',confidence:1}]);renderMath(next)};els.retryRead.onclick=()=>rerunCurrent();if(b?.steps?.length){els.stepsList.replaceChildren(...b.steps.map(s=>{const li=document.createElement('li');li.textContent=s;return li}));els.stepCount.textContent=`${b.steps.length}ステップ`;hide(els.steps,false)}showCandidates([...(a.alternatives||[]),...(state.diagnostic?(a.entries||[]):[])]);els.copy.onclick=()=>copyText(`${b?.expression||els.editableText.value}\n${b?.answer||''}`);els.speak.onclick=()=>speakText(`${b?.expression||els.editableText.value}。${b?.answer||''}`);els.more.onclick=()=>hide(els.candidates,!els.candidates.classList.contains('hidden'));hide(els.result,false)}
function renderText(r){resetResult();state.latest={type:'text',result:r};const b=r.best;els.resultBadge.textContent='TEXT';els.resultTitle.textContent=b.text?'文字を読み取りました':'文字を読み取れません';els.resultMeta.textContent=state.diagnostic?`${b.source} · ${Math.round((b.confidence||0)*100)}%`:'必要なら修正できます';hide(els.editableBlock,false);els.editableLabel.textContent='認識した文字';els.editableText.value=b.text||'';els.applyEdit.textContent='この内容で確定';els.applyEdit.onclick=()=>{b.text=els.editableText.value;renderText(r)};els.retryRead.onclick=()=>rerunCurrent();showCandidates(state.diagnostic?r.entries:[]);els.copy.onclick=()=>copyText(els.editableText.value);els.speak.onclick=()=>speakText(els.editableText.value);els.more.onclick=()=>translateCurrentText();hide(els.result,false)}
function renderTranslation(source,target,direction){resetResult();state.latest={type:'translation',source,target,direction};els.resultBadge.textContent='TRANSLATE';els.resultTitle.textContent=direction==='ja-en'?'日本語 → English':'English → 日本語';els.resultMeta.textContent='端末内モデルで翻訳';els.translationFrom.textContent=source;els.translationTo.textContent=target;hide(els.translationBlock,false);hide(els.editableBlock,false);els.editableLabel.textContent='原文';els.editableText.value=source;els.applyEdit.textContent='この文を翻訳';els.applyEdit.onclick=()=>translateText(els.editableText.value);els.retryRead.onclick=()=>rerunCurrent();els.copy.onclick=()=>copyText(target);els.speak.onclick=()=>speakText(target);els.more.disabled=true;hide(els.result,false)}
function renderColor(c){resetResult();state.latest={type:'color',color:c};els.resultBadge.textContent='COLOR';els.resultTitle.textContent=c.hex;els.resultMeta.textContent='選択範囲の代表色';els.colorSwatch.style.background=c.hex;els.colorHex.textContent=c.hex;els.colorRgb.textContent=`rgb(${c.r}, ${c.g}, ${c.b})`;els.colorHsl.textContent=`hsl(${c.h}, ${c.s}%, ${c.l}%)`;hide(els.colorBlock,false);els.copy.onclick=()=>copyText(c.hex);els.speak.disabled=true;els.more.disabled=true;hide(els.result,false)}

function copyText(t){if(t)navigator.clipboard?.writeText(t).catch(()=>{})}
function speakText(t){if(!t||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang=detectJapanese(t)?'ja-JP':'en-US';speechSynthesis.speak(u)}
function rgbToHsl(r,g,b){r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b);let h=0,s=0,l=(max+min)/2;if(max!==min){const d=max-min;s=l>.5?d/(2-max-min):d/(max+min);switch(max){case r:h=(g-b)/d+(g<b?6:0);break;case g:h=(b-r)/d+2;break;default:h=(r-g)/d+4}h/=6}return[Math.round(h*360),Math.round(s*100),Math.round(l*100)]}
function sampleColor(r){const{sx,sy,sw,sh}=sourceRect(r),c=document.createElement('canvas');c.width=c.height=64;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(els.photo,sx,sy,sw,sh,0,0,64,64);const d=ctx.getImageData(0,0,64,64).data;let rr=0,gg=0,bb=0,n=0;for(let i=0;i<d.length;i+=16){rr+=d[i];gg+=d[i+1];bb+=d[i+2];n++}rr=Math.round(rr/n);gg=Math.round(gg/n);bb=Math.round(bb/n);const hex='#'+[rr,gg,bb].map(v=>v.toString(16).padStart(2,'0')).join('').toUpperCase(),[h,s,l]=rgbToHsl(rr,gg,bb);return{r:rr,g:gg,b:bb,hex,h,s,l}}

function ensureUtilityWorker(){if(utilityWorker)return utilityWorker;utilityWorker=new Worker('./utility-worker.js',{type:'module'});utilityWorker.onmessage=e=>{const m=e.data||{};if(m.type==='progress')progress(m.progress,m.detail);else if(m.type==='result'&&translationResolve){const r=translationResolve;translationResolve=translationReject=null;r(m.text||'')}else if(m.type==='error'&&translationReject){const r=translationReject;translationResolve=translationReject=null;r(Error(m.message||'翻訳エラー'))}};return utilityWorker}
function translateLocal(text,direction){const id=crypto.randomUUID();return new Promise((resolve,reject)=>{translationResolve=resolve;translationReject=reject;ensureUtilityWorker().postMessage({type:'TRANSLATE',id,text,direction})})}
async function translateText(text){if(!text)return;setProcessing(true,'翻訳中','翻訳モデルを準備しています');try{const direction=detectJapanese(text)?'ja-en':'en-ja',target=await translateLocal(text,direction);renderTranslation(text,target,direction)}catch(e){els.resultMeta.textContent='翻訳モデルを読み込めませんでした'}finally{setProcessing(false)}}
async function translateCurrentText(){const text=els.editableText.value.trim();if(text)await translateText(text)}
